/**
 * cardAssets — resolver helpers from gameplay IDs to public asset URLs.
 *
 * Lookup tables live in `generatedAssetMaps.ts` (auto-generated by
 * `scripts/sync-asset-maps.mjs` from `public/assets/d2/generated/`).
 * Run `npm run sync-asset-maps` whenever new art lands.
 *
 * Convention:
 *   gameplay IDs are `<category-prefix>/<key>`; resolvers strip the first
 *   prefix segment before lookup. Returns:
 *     - string  → public URL
 *     - null    → intentionally absent → silhouette
 */

import {
  CLASS_PORTRAITS,
  MONSTER_ART,
  UNIQUE_ITEM_ICONS,
  BASE_ITEM_ICONS,
  ZONE_ART
} from './generatedAssetMaps';
import basesJson from '@/data/items/bases.json';
import uniquesJson from '@/data/items/uniques.json';
import amazonJson from '@/data/classes/amazon.json';
import assassinJson from '@/data/classes/assassin.json';
import barbarianJson from '@/data/classes/barbarian.json';
import druidJson from '@/data/classes/druid.json';
import necromancerJson from '@/data/classes/necromancer.json';
import paladinJson from '@/data/classes/paladin.json';
import sorceressJson from '@/data/classes/sorceress.json';
import act1Json from '@/data/monsters/act1.json';
import act2Json from '@/data/monsters/act2.json';
import act3Json from '@/data/monsters/act3.json';
import act4Json from '@/data/monsters/act4.json';
import act5Json from '@/data/monsters/act5.json';

/**
 * Build a `key → imagePath` override map from a JSON entries array.
 * `key` strips the leading `<category>/` prefix the way `stripPrefix` does.
 */
interface JsonEntryWithImage { readonly id?: unknown; readonly imagePath?: unknown }
function collectOverrides(entries: readonly unknown[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const raw of entries) {
    if (!raw || typeof raw !== 'object') continue;
    const e = raw as JsonEntryWithImage;
    const id = typeof e.id === 'string' ? e.id : null;
    const img = typeof e.imagePath === 'string' && e.imagePath.length > 0 ? e.imagePath : null;
    if (id && img) {
      out[id] = img;
      const slash = id.indexOf('/');
      if (slash !== -1) out[id.slice(slash + 1)] = img;
    }
  }
  return out;
}

const CLASS_OVERRIDES = collectOverrides([
  amazonJson, assassinJson, barbarianJson, druidJson, necromancerJson, paladinJson, sorceressJson
]);
const MONSTER_OVERRIDES = collectOverrides([
  ...(act1Json as readonly unknown[]),
  ...(act2Json as readonly unknown[]),
  ...(act3Json as readonly unknown[]),
  ...(act4Json as readonly unknown[]),
  ...(act5Json as readonly unknown[])
]);
const ITEM_OVERRIDES: Record<string, string> = {
  ...collectOverrides(basesJson as readonly unknown[]),
  ...collectOverrides(uniquesJson as readonly unknown[])
};

/** Prefix-rule table for mercenary archetype proxying. First match wins. */
const MERC_ARCHETYPE_RULES: readonly (readonly [prefix: string, archetype: string | null])[] = [
  ['act1-rogue-', 'rogue-archer'],
  ['act3-iron-wolf-', 'iron-wolf'],
  ['act3-militia-', 'desert-mercenary'],
  ['act5-barbarian-', 'barbarian-warrior'],
  ['act2-', 'desert-mercenary'],
  ['act4-paladin-', null],
  ['tavern-thief-', null],
  ['tavern-acolyte-', null]
];

/** Class-portrait proxies for mercs whose archetype matches a hero class. */
const MERC_ARCHETYPES: Readonly<Record<string, string | undefined>> = {
  'rogue-archer': CLASS_PORTRAITS.amazon,
  'desert-mercenary': CLASS_PORTRAITS.barbarian,
  'iron-wolf': CLASS_PORTRAITS.sorceress,
  'barbarian-warrior': CLASS_PORTRAITS.barbarian
};

/** Strip the first `<category>/` prefix segment if present. */
function stripPrefix(id: string): string {
  const slash = id.indexOf('/');
  return slash === -1 ? id : id.slice(slash + 1);
}

/** dev-only warn helper (no-op in production). Vite-native env check. */
function warnMissing(category: string, key: string): void {
  // import.meta.env.DEV is statically replaced by Vite in production builds.
  if (import.meta.env.DEV) {
    // eslint-disable-next-line no-console
    console.warn(`[cardAssets] missing ${category} key: ${key}`);
  }
}

export function resolveClassPortrait(classId: string): string | null {
  const key = stripPrefix(classId);
  if (classId in CLASS_OVERRIDES) return CLASS_OVERRIDES[classId] ?? null;
  if (key in CLASS_OVERRIDES) return CLASS_OVERRIDES[key] ?? null;
  if (key in CLASS_PORTRAITS) return CLASS_PORTRAITS[key] ?? null;
  warnMissing('class', key);
  return null;
}

export function resolveMonsterArt(monsterId: string): string | null {
  const key = stripPrefix(monsterId);
  if (monsterId in MONSTER_OVERRIDES) return MONSTER_OVERRIDES[monsterId] ?? null;
  if (key in MONSTER_OVERRIDES) return MONSTER_OVERRIDES[key] ?? null;
  if (key in MONSTER_ART) return MONSTER_ART[key] ?? null;
  warnMissing('monster', key);
  return null;
}

/**
 * Infer a base-icon archetype from a base-item slug.
 *
 * Examples:
 *   `wp1h-short-sword`  → `sword`
 *   `weapon-axe-large`  → `axe`
 *   `helm-cap`          → `helm`
 *   `armor-leather`     → `armor`
 *   `glove-leather`     → `gloves`
 *   `boots`             → `boots`
 *   `sh-buckler`        → `shield`
 *   `belt-light`        → `belt`
 */
function inferBaseArchetype(slug: string): string | null {
  if (/^wp1h-|^wp2h-|^weapon-sword/.test(slug)) return 'sword';
  if (slug.startsWith('weapon-axe')) return 'axe';
  if (slug.startsWith('weapon-mace')) return 'mace';
  if (/^weapon-bow|^weapon-crossbow/.test(slug)) return 'bow';
  if (/^weapon-staff|^weapon-wand|^weapon-scepter/.test(slug)) return 'staff';
  if (/^weapon-dagger|^weapon-knife/.test(slug)) return 'dagger';
  if (slug.startsWith('helm-')) return 'helm';
  if (slug.startsWith('armor-')) return 'armor';
  if (slug.startsWith('glove-')) return 'gloves';
  if (slug.startsWith('boot')) return 'boots';
  if (slug.startsWith('belt-')) return 'belt';
  if (/^sh-|^shield-/.test(slug)) return 'shield';
  if (slug.startsWith('ring')) return 'ring';
  if (slug.startsWith('amulet')) return 'amulet';
  if (/^potion-(red|health|life)/.test(slug)) return 'potion-health';
  if (/^potion-(blue|mana)/.test(slug)) return 'potion-mana';
  if (slug.startsWith('rune')) return 'rune';
  if (slug.startsWith('gem')) return 'gem';
  if (slug.startsWith('scroll')) return 'scroll';
  return null;
}

/**
 * Resolve an item-icon URL from a base or unique id. Accepts both
 *   - bare `unique.<slug>`            → unique icon
 *   - prefixed `items/unique/<slug>`  → unique icon
 *   - prefixed `items/base/<slug>`    → base archetype icon (sword/helm/...)
 *
 * Returns `null` for ids we can't classify (caller renders silhouette).
 */
export function resolveItemIcon(baseId: string): string | null {
  if (!baseId) return null;
  const key = stripPrefix(baseId);

  // 0) JSON-driven override (devtool `imagePath` field).
  if (baseId in ITEM_OVERRIDES) return ITEM_OVERRIDES[baseId] ?? null;
  if (key in ITEM_OVERRIDES) return ITEM_OVERRIDES[key] ?? null;

  // 1) Unique items: `unique.<slug>` or `unique/<slug>`
  const uniqueMatch = /^unique[./](.+)$/.exec(key);
  if (uniqueMatch?.[1]) {
    const slug = uniqueMatch[1];
    if (slug in UNIQUE_ITEM_ICONS) return UNIQUE_ITEM_ICONS[slug] ?? null;
    // Many uniques have no dedicated art yet — silent silhouette.
    return null;
  }

  // 2) Base items: `base.<slug>` or `base/<slug>`
  const baseMatch = /^base[./](.+)$/.exec(key);
  if (baseMatch?.[1]) {
    const inferred = inferBaseArchetype(baseMatch[1]);
    if (inferred && inferred in BASE_ITEM_ICONS) {
      return BASE_ITEM_ICONS[inferred] ?? null;
    }
  }

  // 3) Direct archetype id (e.g. `sword`) — used by tests and synthetic callers.
  if (key in BASE_ITEM_ICONS) return BASE_ITEM_ICONS[key] ?? null;

  return null;
}

export function resolveZoneArt(zoneId: string): string | null {
  const key = stripPrefix(zoneId);
  if (key in ZONE_ART) return ZONE_ART[key] ?? null;
  warnMissing('zone', key);
  return null;
}

/**
 * Resolve a mercenary's portrait. Today no merc has dedicated art; we
 * proxy via class portraits using the prefix-rule table. Falls back to
 * the closest class portrait based on prefix; null if no rule matches.
 */
export function resolveMercArt(mercId: string): string | null {
  const key = stripPrefix(mercId);
  // 1) exact match against canonical archetype keys
  if (key in MERC_ARCHETYPES) return MERC_ARCHETYPES[key] ?? null;
  // 2) prefix-rule walk
  for (const [prefix, archetype] of MERC_ARCHETYPE_RULES) {
    if (key.startsWith(prefix)) {
      if (archetype === null) return null;
      return MERC_ARCHETYPES[archetype] ?? null;
    }
  }
  // 3) classRef-style fallback (e.g. `barbarian` → class portrait)
  const classBase = key.split(/[#-]/)[0] ?? key;
  if (classBase in CLASS_PORTRAITS) return CLASS_PORTRAITS[classBase] ?? null;
  return null;
}
