/**
 * cardAssets — resolver helpers from gameplay IDs to public asset URLs.
 *
 * Lookup tables live in `generatedAssetMaps.ts` (auto-generated by
 * `scripts/sync-asset-maps.mjs` from `public/assets/d2/generated/`).
 * Run `npm run sync-asset-maps` whenever new art lands.
 *
 * Convention:
 *   gameplay IDs are `<category-prefix>/<key>`; resolvers strip the first
 *   prefix segment before lookup. Returns:
 *     - string  → public URL
 *     - null    → intentionally absent → silhouette
 */

import {
  CLASS_PORTRAITS,
  MERC_PORTRAITS,
  MONSTER_ART,
  UNIQUE_ITEM_ICONS,
  BASE_ITEM_ICONS,
  ZONE_ART,
  SKILL_ICONS
} from './generatedAssetMaps';
import { getImageOverride } from './imageOverrides';

/** Prefix-rule table for mercenary archetype proxying. First match wins. */
const MERC_ARCHETYPE_RULES: readonly (readonly [prefix: string, archetype: string | null])[] = [
  ['act1-rogue-', 'rogue-archer'],
  ['act3-iron-wolf-', 'iron-wolf'],
  ['act3-militia-', 'desert-mercenary'],
  ['act5-barbarian-', 'barbarian-warrior'],
  ['act2-', 'desert-mercenary'],
  ['act4-paladin-', null],
  ['tavern-thief-', null],
  ['tavern-acolyte-', null]
];

/** Class-portrait proxies for mercs whose archetype matches a hero class. */
const MERC_ARCHETYPES: Readonly<Record<string, string | undefined>> = {
  'rogue-archer': CLASS_PORTRAITS.amazon,
  'desert-mercenary': CLASS_PORTRAITS.barbarian,
  'iron-wolf': CLASS_PORTRAITS.sorceress,
  'barbarian-warrior': CLASS_PORTRAITS.barbarian
};

/** Strip the first `<category>/` prefix segment if present. */
function stripPrefix(id: string): string {
  const slash = id.indexOf('/');
  return slash === -1 ? id : id.slice(slash + 1);
}

function normalizeMercPortraitKey(key: string): string {
  const base = key.split('#')[0] ?? key;
  const match = /^(act[1-5])[-.](.+)$/.exec(base);
  if (!match?.[1] || !match[2]) return base;
  return `${match[1]}.${match[2]}`;
}

function firstExistingBaseIcon(...candidates: readonly (string | null | undefined)[]): string | null {
  for (const candidate of candidates) {
    if (candidate && candidate in BASE_ITEM_ICONS) return BASE_ITEM_ICONS[candidate] ?? null;
  }
  return null;
}

/** dev-only warn helper (no-op in production). Vite-native env check. */
function warnMissing(category: string, key: string): void {
  // import.meta.env.DEV is statically replaced by Vite in production builds.
  if (import.meta.env.DEV) {
    // eslint-disable-next-line no-console
    console.warn(`[cardAssets] missing ${category} key: ${key}`);
  }
}

export function resolveClassPortrait(classId: string): string | null {
  const key = stripPrefix(classId);
  const override = getImageOverride('class', key);
  if (override) return override;
  if (key in CLASS_PORTRAITS) return CLASS_PORTRAITS[key] ?? null;
  warnMissing('class', key);
  return null;
}

export function resolveMonsterArt(monsterId: string): string | null {
  const key = stripPrefix(monsterId);
  const override = getImageOverride('monster', key);
  if (override) return override;
  if (key in MONSTER_ART) return MONSTER_ART[key] ?? null;
  warnMissing('monster', key);
  return null;
}

/**
 * Infer a base-icon archetype from a base-item slug.
 *
 * Examples:
 *   `wp1h-short-sword`  → `sword`
 *   `wp2h-great-axe`    → `axe`
 *   `wp2h-war-pike`     → `staff` (generic polearm fallback)
 *   `weapon-axe-large`  → `axe`
 *   `helm-cap`          → `helm`
 *   `armor-leather`     → `armor`
 *   `glove-leather`     → `gloves`
 *   `boots`             → `boots`
 *   `sh-buckler`        → `shield`
 *   `belt-light`        → `belt`
 */
function inferBaseArchetype(slug: string): string | null {
  if (/^wp1h-|^weapon-sword/.test(slug)) return 'sword';
  if (/^wp2h-(two-handed-sword|colossus-blade)/.test(slug)) return 'sword';
  if (/^wp2h-(great-axe)/.test(slug)) return 'axe';
  if (/^wp2h-(thunder-maul)/.test(slug)) return 'mace';
  if (/^wp2h-(war-pike|giant-thresher)/.test(slug)) return 'staff';
  if (slug.startsWith('weapon-axe')) return 'axe';
  if (slug.startsWith('weapon-mace')) return 'mace';
  if (/^weapon-bow|^weapon-crossbow/.test(slug)) return 'bow';
  if (/^weapon-staff|^weapon-wand|^weapon-scepter|^weapon-polearm/.test(slug)) return 'staff';
  if (/^weapon-dagger|^weapon-knife/.test(slug)) return 'dagger';
  if (slug.startsWith('helm-')) return 'helm';
  if (slug.startsWith('armor-')) return 'armor';
  if (slug === 'gloves' || slug.startsWith('glove-')) return 'gloves';
  if (slug.startsWith('boot')) return 'boots';
  if (slug === 'belt' || slug.startsWith('belt-')) return 'belt';
  if (/^sh-|^shield-/.test(slug)) return 'shield';
  if (slug.startsWith('ring')) return 'ring';
  if (slug.startsWith('amulet') || slug.startsWith('amu-')) return 'amulet';
  if (/^potion-(red|health|life)/.test(slug)) return 'potion-health';
  if (/^potion-(blue|mana)/.test(slug)) return 'potion-mana';
  if (slug.startsWith('rune')) return 'rune';
  if (slug.startsWith('gem')) return 'gem';
  if (slug.startsWith('scroll')) return 'scroll';
  return null;
}

function inferSetArchetype(itemIds: readonly string[] | undefined): string | null {
  for (const itemId of itemIds ?? []) {
    const leaf = itemId.split('/').pop() ?? '';
    const inferred = inferBaseArchetype(leaf);
    if (inferred) return inferred;
    if (leaf === 'weapon') return 'sword';
    if (leaf === 'armor') return 'armor';
    if (leaf === 'helm') return 'helm';
    if (leaf === 'shield') return 'shield';
    if (leaf === 'amulet') return 'amulet';
    if (leaf === 'ring') return 'ring';
    if (leaf === 'gloves') return 'gloves';
    if (leaf === 'belt') return 'belt';
    if (leaf === 'boots') return 'boots';
  }
  return null;
}

export interface ItemIconContext {
  /** Template base for definition-backed uniques / set pieces. */
  readonly baseId?: string;
  /** Runeword allowed base types from `src/data/items/runewords.json`. */
  readonly allowedBases?: readonly string[];
  /** Set-definition member ids from `src/data/items/sets.json`. */
  readonly setItemIds?: readonly string[];
}

/**
 * Resolve an item-icon URL from a base or unique id. Accepts both
 *   - bare `unique.<slug>`            → unique icon
 *   - prefixed `items/unique/<slug>`  → unique icon
 *   - prefixed `items/base/<slug>`    → base archetype icon (sword/helm/...)
 *   - `runes/<slug>`                  → generic rune icon
 *   - `runewords/<slug>`              → generic rune icon
 *   - `sets/<slug>`                   → inferred first-piece archetype icon
 *
 * Returns `null` for ids we can't classify (caller renders silhouette).
 */
export function resolveItemIcon(itemId: string, context: ItemIconContext = {}): string | null {
  if (!itemId) return null;
  const key = stripPrefix(itemId);

  // Override takes precedence over inferred archetype lookup.
  const override = getImageOverride('item', key);
  if (override) return override;

  // 1) Unique items: `unique.<slug>` or `unique/<slug>`
  const uniqueMatch = /^unique[./](.+)$/.exec(key);
  if (uniqueMatch?.[1]) {
    const slug = uniqueMatch[1];
    if (slug in UNIQUE_ITEM_ICONS) return UNIQUE_ITEM_ICONS[slug] ?? null;
    if (context.baseId) return resolveItemIcon(context.baseId);
    return null;
  }

  // 2) Base items: `base.<slug>` or `base/<slug>`
  const baseMatch = /^base[./](.+)$/.exec(key);
  if (baseMatch?.[1]) {
    const inferred = inferBaseArchetype(baseMatch[1]);
    if (inferred && inferred in BASE_ITEM_ICONS) {
      return BASE_ITEM_ICONS[inferred] ?? null;
    }
  }

  // 3) Rune items share the canonical generated rune icon.
  if (itemId.startsWith('runes/') || /^rune[./-]/.test(key)) {
    return firstExistingBaseIcon('rune');
  }

  // 4) Runeword definitions are recipes, not concrete equipped bases.
  if (itemId.startsWith('runewords/') || /^runeword[./-]/.test(key)) {
    if (context.baseId) return resolveItemIcon(context.baseId);
    return firstExistingBaseIcon('rune');
  }

  // 5) Set definitions/pieces use a concrete base when supplied; otherwise
  // infer a representative first-piece archetype and fall back to gem.
  if (itemId.startsWith('sets/') || /^set[./-]/.test(key)) {
    if (context.baseId) return resolveItemIcon(context.baseId);
    const inferred = inferSetArchetype(context.setItemIds);
    return firstExistingBaseIcon(inferred, 'gem');
  }

  // 6) Direct archetype id (e.g. `sword`) — used by tests and synthetic callers.
  if (key in BASE_ITEM_ICONS) return BASE_ITEM_ICONS[key] ?? null;

  return null;
}

export function resolveZoneArt(zoneId: string): string | null {
  const key = stripPrefix(zoneId);
  if (key in ZONE_ART) return ZONE_ART[key] ?? null;
  warnMissing('zone', key);
  return null;
}

export function normalizeSkillIconKey(skillRef: string): string | null {
  const trimmed = skillRef.trim();
  if (!trimmed) return null;

  const pathMatch = /^skills\/([a-z0-9-]+)\/([a-z0-9-]+)(?:\.png)?$/i.exec(trimmed);
  if (pathMatch?.[1] && pathMatch[2]) {
    return `skills.${pathMatch[1].toLowerCase()}.${pathMatch[2].toLowerCase()}`;
  }

  const dataIdMatch = /^skills-(amazon|assassin|barbarian|druid|necromancer|paladin|sorceress)-(.+)$/i.exec(trimmed);
  if (dataIdMatch?.[1] && dataIdMatch[2]) {
    return `skills.${dataIdMatch[1].toLowerCase()}.${dataIdMatch[2].toLowerCase()}`;
  }

  const dottedMatch = /^skills\.([a-z0-9-]+)\.([a-z0-9-]+)$/i.exec(trimmed);
  if (dottedMatch?.[1] && dottedMatch[2]) {
    return `skills.${dottedMatch[1].toLowerCase()}.${dottedMatch[2].toLowerCase()}`;
  }

  return null;
}

export function resolveSkillIcon(skillRef: string): string | null {
  const key = normalizeSkillIconKey(skillRef);
  if (!key) return null;
  const override = getImageOverride('skill', key);
  if (override) return override;
  if (key in SKILL_ICONS) return SKILL_ICONS[key] ?? null;
  return null;
}

/**
 * Resolve a mercenary's portrait. Dedicated merc portraits win first;
 * class-portrait proxies are only a fallback for legacy/non-hireable mercs.
 */
export function resolveMercArt(mercId: string): string | null {
  const stripped = stripPrefix(mercId);
  const key = stripped.split('#')[0] ?? stripped;
  // 0) Manual override wins over all inferred logic.
  const override = getImageOverride('merc', key);
  if (override) return override;

  // 1) exact dedicated portrait, e.g. `act1-rogue-fire` → `act1.rogue-fire`.
  const portraitKey = normalizeMercPortraitKey(key);
  if (portraitKey in MERC_PORTRAITS) return MERC_PORTRAITS[portraitKey] ?? null;

  // 2) exact match against canonical archetype keys
  if (key in MERC_ARCHETYPES) return MERC_ARCHETYPES[key] ?? null;
  // 3) prefix-rule walk
  for (const [prefix, archetype] of MERC_ARCHETYPE_RULES) {
    if (key.startsWith(prefix)) {
      if (archetype === null) return null;
      return MERC_ARCHETYPES[archetype] ?? null;
    }
  }
  // 4) classRef-style fallback (e.g. `barbarian` → class portrait)
  const classBase = key.split(/[#-]/)[0] ?? key;
  if (classBase in CLASS_PORTRAITS) return CLASS_PORTRAITS[classBase] ?? null;
  return null;
}
