import type { Rng } from '../rng';
import type { Affix, AffixRoll, Item, ItemBase, ItemBaseType, ItemStatKey, Rarity } from '../types/items';
export interface RarityAffixRange { readonly min: number; readonly max: number }
export interface RarityAffixCount { readonly prefix: RarityAffixRange; readonly suffix: RarityAffixRange; readonly total?: RarityAffixRange }
export type RarityAffixRules = Readonly<Partial<Record<Rarity, RarityAffixCount>>>;
export interface RollItemInput { readonly baseId: string; readonly rarity: Rarity; readonly ilvl: number }
export interface ItemRollPools { readonly bases: ReadonlyMap<string, ItemBase>; readonly affixes: readonly Affix[]; readonly rarityRules?: RarityAffixRules }
let itemSeq = 0; export function __resetRollItemSeqForTests(): void { itemSeq = 0; }
function nextItemId(rng: Rng): string { itemSeq = (itemSeq + 1) >>> 0; return `it-${rng.nextInt(0, 0xffffff).toString(36)}-${itemSeq.toString(36)}`; }
function defaultRules(rarity: Rarity): RarityAffixCount { if (rarity === 'magic') return { prefix:{min:1,max:1}, suffix:{min:1,max:1} }; if (rarity === 'rare') return { prefix:{min:1,max:3}, suffix:{min:1,max:3}, total:{min:4,max:6} }; return { prefix:{min:0,max:0}, suffix:{min:0,max:0}, total:{min:0,max:0} }; }
function rulesFor(rarity: Rarity, rules?: RarityAffixRules): RarityAffixCount { return rules?.[rarity] ?? defaultRules(rarity); }
function rollBaseStats(base: ItemBase, rng: Rng): Partial<Record<ItemStatKey, number>> { const rolls: Partial<Record<ItemStatKey, number>> = {}; if (base.baseDamage) rolls.attack = rng.nextInt(Math.ceil(base.baseDamage.min), Math.floor(base.baseDamage.max)); if (typeof base.baseDefense === 'number' && base.baseDefense > 0) { const v = Math.max(1, Math.round(base.baseDefense * 0.15)); rolls.defense = rng.nextInt(Math.max(1, base.baseDefense - v), base.baseDefense + v); } return rolls; }
function tierIndexFor(affix: Affix, ilvl: number): number | undefined { let chosen: number | undefined; affix.tiers.forEach((tier, index) => { if (ilvl >= tier.ilvlMin && ilvl <= tier.ilvlMax) chosen = index; }); return chosen; }
function appliesTo(affix: Affix, type: ItemBaseType): boolean { return affix.appliesTo.length === 0 || affix.appliesTo.includes(type); }
function pickWeighted(pool: readonly Affix[], rarity: Rarity, rng: Rng): Affix | undefined { const weighted = pool.map((affix) => ({ affix, weight: affix.rarityWeights[rarity] ?? 0 })).filter((entry) => entry.weight > 0); const total = weighted.reduce((sum, entry) => sum + entry.weight, 0); if (total <= 0) return undefined; let roll = rng.next() * total; for (const entry of weighted) { roll -= entry.weight; if (roll <= 0) return entry.affix; } return weighted[weighted.length - 1]?.affix; }
function takeAffix(remaining: Affix[], kind: 'prefix' | 'suffix', rarity: Rarity, ilvl: number, rng: Rng): AffixRoll | undefined { const pool = remaining.filter((affix) => affix.kind === kind && tierIndexFor(affix, ilvl) !== undefined); const picked = pickWeighted(pool, rarity, rng); if (!picked) return undefined; const tierIndex = tierIndexFor(picked, ilvl); if (tierIndex === undefined) return undefined; const tier = picked.tiers[tierIndex]; if (!tier) return undefined; const idx = remaining.findIndex((affix) => affix.id === picked.id); if (idx >= 0) remaining.splice(idx, 1); return { id: picked.id, tier: tierIndex, rolledValue: rng.nextInt(tier.valueMin, tier.valueMax) }; }
function rollCounts(rarity: Rarity, rules: RarityAffixCount, rng: Rng): { prefix: number; suffix: number } { if (rarity === 'rare') { const totalRule = rules.total ?? { min: 4, max: 6 }; const total = rng.nextInt(totalRule.min, totalRule.max); const minPrefix = Math.max(rules.prefix.min, total - rules.suffix.max); const maxPrefix = Math.min(rules.prefix.max, total - rules.suffix.min); const prefix = rng.nextInt(minPrefix, maxPrefix); return { prefix, suffix: total - prefix }; } return { prefix: rng.nextInt(rules.prefix.min, rules.prefix.max), suffix: rng.nextInt(rules.suffix.min, rules.suffix.max) }; }
function rollAffixes(base: ItemBase, rarity: Rarity, ilvl: number, affixes: readonly Affix[], rules: RarityAffixCount, rng: Rng): readonly AffixRoll[] { if (rarity !== 'magic' && rarity !== 'rare') return []; if (!base.canHaveAffixes) return []; const counts = rollCounts(rarity, rules, rng); const remaining = affixes.filter((affix) => appliesTo(affix, base.type)); const rolled: AffixRoll[] = []; for (let i = 0; i < counts.prefix; i += 1) { const roll = takeAffix(remaining, 'prefix', rarity, ilvl, rng); if (roll) rolled.push(roll); } for (let i = 0; i < counts.suffix; i += 1) { const roll = takeAffix(remaining, 'suffix', rarity, ilvl, rng); if (roll) rolled.push(roll); } return rolled; }
export function rollItem(input: RollItemInput, pools: ItemRollPools, rng: Rng): Item | undefined { const base = pools.bases.get(input.baseId); if (!base) return undefined; const ilvl = input.ilvl; const affixes = rollAffixes(base, input.rarity, ilvl, pools.affixes, rulesFor(input.rarity, pools.rarityRules), rng); return { id: nextItemId(rng), baseId: base.id, rarity: input.rarity, level: ilvl, ilvl, baseRolls: rollBaseStats(base, rng), affixes, generatedName: {}, identified: input.rarity === 'normal' || input.rarity === 'magic', equipped: false }; }
