"""Generator for src/data/items/uniques.json and sets.json.

Expands the existing dataset to cover the Diablo II: LoD canon while
preserving every existing canonical entry (after de-duplicating colliding
ids).  Stat numbers are the most-commonly cited LoD 1.14 values; flavor
text is paraphrased in our own words and kept short.

Run:
    python scripts/gen-uniques-sets.py
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional, Tuple

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UNIQUES_PATH = os.path.join(ROOT, "src", "data", "items", "uniques.json")
SETS_PATH = os.path.join(ROOT, "src", "data", "items", "sets.json")
DOC_PATH = os.path.join(ROOT, "docs", "design", "uniques-base-mapping.md")

# ---------------------------------------------------------------------------
# Base picker — maps an abstract slot/tier to an existing baseId.
# ---------------------------------------------------------------------------

# (slot key) -> list of (reqLevel, baseId), sorted ascending
BASE_BY_SLOT: Dict[str, List[Tuple[int, str]]] = {
    "helm": [
        (1,  "items/base/helm-cap"),
        (5,  "items/base/helm-skull-cap"),
        (22, "items/base/helm-war-hat"),
        (28, "items/base/helm-casque"),
        (45, "items/base/helm-armet"),
        (55, "items/base/helm-giant-conch"),
    ],
    "chest": [
        (1,  "items/base/armor-quilted"),
        (6,  "items/base/armor-leather"),
        (10, "items/base/armor-light"),
        (25, "items/base/armor-chain-mail"),
        (32, "items/base/armor-breast-plate"),
        (40, "items/base/armor-heavy"),
        (50, "items/base/armor-dusk-shroud"),
        (60, "items/base/armor-archon-plate"),
    ],
    "gloves": [
        (1,  "items/base/glove-leather"),
        (7,  "items/base/glove-heavy"),
        (24, "items/base/glove-chain"),
        (30, "items/base/glove-light-gauntlets"),
        (48, "items/base/glove-vampirebone"),
        (58, "items/base/glove-bramble-mitts"),
    ],
    "boots": [
        (1,  "items/base/boot-leather"),
        (7,  "items/base/boot-heavy"),
        (24, "items/base/boot-chain"),
        (30, "items/base/boot-light-plated"),
        (48, "items/base/boot-demonhide"),
        (58, "items/base/boot-myrmidon-greaves"),
    ],
    "belt": [
        (1,  "items/base/belt-sash"),
        (7,  "items/base/belt-light"),
        (22, "items/base/belt-heavy"),
        (30, "items/base/belt-plated"),
        (48, "items/base/belt-demonhide"),
        (58, "items/base/belt-mithril-coil"),
    ],
    "shield": [
        (1,  "items/base/sh-buckler"),
        (8,  "items/base/sh-kite"),
        (25, "items/base/sh-aegis"),
        (35, "items/base/sh-dragon-shield"),
        (50, "items/base/sh-monarch"),
        (60, "items/base/sh-sacred-targe"),
    ],
    "sword1h": [
        (1,  "items/base/wp1h-short-sword"),
        (8,  "items/base/wp1h-scimitar"),
        (22, "items/base/wp1h-long-sword"),
        (32, "items/base/wp1h-war-sword"),
        (50, "items/base/wp1h-phase-blade"),
        (60, "items/base/wp1h-legend-sword"),
    ],
    "sword2h": [
        (1,  "items/base/wp2h-two-handed-sword"),
        (8,  "items/base/wp2h-great-axe"),
        (24, "items/base/wp2h-war-pike"),
        (35, "items/base/wp2h-giant-thresher"),
        (52, "items/base/wp2h-colossus-blade"),
        (62, "items/base/wp2h-thunder-maul"),
    ],
    "ring": [
        (1,  "items/base/ring-iron"),
        (10, "items/base/ring-silver"),
        (25, "items/base/ring-jade"),
        (35, "items/base/ring-amber"),
        (50, "items/base/ring-obsidian"),
        (60, "items/base/ring-zircon"),
    ],
    "amulet": [
        (1,  "items/base/amu-tin"),
        (10, "items/base/amu-brass"),
        (25, "items/base/amu-silver"),
        (35, "items/base/amu-jade"),
        (50, "items/base/amu-obsidian"),
        (60, "items/base/amu-zircon"),
    ],
}

# Single-tier weapon bases (closest-fit for many real D2 bases).
SINGLE = {
    "bow":      "items/base/weapon-bow",      # 10
    "crossbow": "items/base/weapon-crossbow", # 15
    "polearm":  "items/base/weapon-polearm",  # 20
    "wand":     "items/base/weapon-wand",     # 5
    "scepter":  "items/base/weapon-scepter",  # 15
    "mace":     "items/base/weapon-mace",     # 10
    "axe":      "items/base/weapon-axe",      # 12
}


def base_for(slot: str, req: int) -> str:
    """Pick the highest base in `slot` whose reqLevel <= req."""
    if slot in SINGLE:
        return SINGLE[slot]
    tiers = BASE_BY_SLOT[slot]
    chosen = tiers[0][1]
    for r, bid in tiers:
        if r <= req:
            chosen = bid
        else:
            break
    return chosen


# ---------------------------------------------------------------------------
# Data: new unique items.
#
# Format:
#     (id_slug, name, slot_key, req_level, stats_dict, flavor_or_None,
#      explicit_baseId_or_None)
#
# `slot_key` is one of BASE_BY_SLOT keys plus SINGLE keys.
# Stat numbers reflect LoD 1.14 canon where readily known; otherwise
# scaled reasonably for the tier. Flavor text is original prose.
# ---------------------------------------------------------------------------

# Convenience builders
def cs(strength=None, dexterity=None, vitality=None, energy=None) -> Dict[str, int]:
    out = {}
    if strength is not None: out["strength"] = strength
    if dexterity is not None: out["dexterity"] = dexterity
    if vitality is not None: out["vitality"] = vitality
    if energy is not None: out["energy"] = energy
    return out

def res(fire=None, cold=None, lightning=None, poison=None, arcane=None, physical=None) -> Dict[str, float]:
    out = {}
    if fire is not None: out["fire"] = fire
    if cold is not None: out["cold"] = cold
    if lightning is not None: out["lightning"] = lightning
    if poison is not None: out["poison"] = poison
    if arcane is not None: out["arcane"] = arcane
    if physical is not None: out["physical"] = physical
    return out

def sm(**kw) -> Dict[str, float]:
    return {k: v for k, v in kw.items() if v is not None}

def dmg(min_, max_, **breakdown) -> Dict[str, Any]:
    return {"min": min_, "max": max_, "breakdown": breakdown}

def s(coreStats=None, resistances=None, statMods=None, grantsSkills=None, damageBonus=None) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    if coreStats: out["coreStats"] = coreStats
    if resistances: out["resistances"] = resistances
    if statMods: out["statMods"] = statMods
    if grantsSkills: out["grantsSkills"] = grantsSkills
    if damageBonus: out["damageBonus"] = damageBonus
    return out


# Each row: (slug, name, slot, req, stats, flavor)
NEW_UNIQUES: List[Tuple[str, str, str, int, Dict[str, Any], Optional[str]]] = [
    # ============== HELMS (Classic) ==============
    ("biggin-bonnet", "Biggin's Bonnet", "helm", 3,
     s(coreStats=cs(strength=5), statMods=sm(life=15, mana=15, attack=20)),
     "A jester's cap, lucky to a fault."),
    ("coif-of-glory", "Coif of Glory", "helm", 9,
     s(statMods=sm(defense=20, life=10), resistances=res(lightning=15)),
     "A worn coif blessed by a long-dead king."),
    ("duskdeep", "Duskdeep", "helm", 12,
     s(statMods=sm(defense=30, life=15), resistances=res(fire=15, lightning=15)),
     "A helm that drinks the dusk."),
    ("howltusk", "Howltusk", "helm", 14,
     s(coreStats=cs(strength=8), statMods=sm(defense=30, attack=30)),
     "Tusks of a slain boar-king set in iron."),
    ("undead-crown", "Undead Crown", "helm", 26,
     s(coreStats=cs(strength=10), statMods=sm(life=20, defense=40), resistances=res(poison=15)),
     "Worn by the puppet-king of a forgotten crypt."),
    ("face-of-horror", "The Face of Horror", "helm", 4,
     s(coreStats=cs(strength=10), statMods=sm(defense=15), resistances=res(fire=10, cold=10, lightning=10, poison=10, arcane=10)),
     "Carven from a twisted gargoyle's likeness."),
    ("peasant-crown", "Peasant Crown", "helm", 28,
     s(coreStats=cs(vitality=20), statMods=sm(life=30, mana=30, defense=50)),
     "A simple circlet that brought a serf to glory."),
    ("rockstopper", "Rockstopper", "helm", 31,
     s(coreStats=cs(vitality=15), statMods=sm(defense=80, life=40), resistances=res(fire=20, cold=20, lightning=20)),
     "Forged of the sturdiest stone."),
    ("stealskull", "Stealskull", "helm", 35,
     s(statMods=sm(magicFind=30, attackSpeed=20, defense=50)),
     "A thief's prized helm — fortune flocks to its wearer."),
    ("darksight-helm", "Darksight Helm", "helm", 38,
     s(coreStats=cs(dexterity=10), statMods=sm(defense=60, magicDodge=10)),
     "Casts an eerie veil over the wearer's face."),
    ("blackhorn-face", "Blackhorn's Face", "helm", 41,
     s(statMods=sm(defense=80), resistances=res(lightning=25, poison=25)),
     "Twin black horns rise from the brow."),
    ("valkyrie-wing", "Valkyrie Wing", "helm", 44,
     s(coreStats=cs(strength=10, dexterity=10), statMods=sm(life=20, mana=20)),
     "A winged helm worn by a fallen battle-maid."),
    ("crown-of-thieves", "Crown of Thieves", "helm", 49,
     s(coreStats=cs(vitality=25), statMods=sm(life=40, goldFind=80, magicFind=20)),
     "A crown stolen from a king who stole it first."),
    ("veil-of-steel", "Veil of Steel", "helm", 53,
     s(coreStats=cs(strength=15, vitality=15), statMods=sm(defense=120),
       resistances=res(fire=25, cold=25, lightning=25, poison=25)),
     "An indomitable steel mask that turns aside all elements."),
    ("nightwing-veil", "Nightwing's Veil", "helm", 67,
     s(coreStats=cs(dexterity=10, energy=15), statMods=sm(defense=100),
       resistances=res(cold=15), damageBonus=dmg(0, 6, cold=6)),
     "Shadow-silk woven into a sorcerer's diadem."),
    ("demonhorn-edge", "Demonhorn's Edge", "helm", 67,
     s(coreStats=cs(strength=20), statMods=sm(defense=120, attack=80),
       resistances=res(fire=20)),
     "Carved from the horn of a slain pit lord."),
    ("cure-all", "Cure-All", "helm", 64,
     s(coreStats=cs(vitality=20), statMods=sm(life=80, defense=70),
       resistances=res(poison=40)),
     "A potion-maker's helm — heals all manner of ills."),
    ("halaberd-reign", "Halaberd's Reign", "helm", 72,
     s(coreStats=cs(strength=25), statMods=sm(defense=150),
       resistances=res(fire=20, cold=20, lightning=20)),
     "A war-king's helm, never bowed."),
    ("wolfhowl", "Wolfhowl", "helm", 79,
     s(coreStats=cs(strength=20, dexterity=10), statMods=sm(defense=140, attack=100)),
     "A druid pelt-helm that sings of the moon."),

    # ============== BODY ARMOR ==============
    ("greyform", "Greyform", "chest", 7,
     s(coreStats=cs(dexterity=5), statMods=sm(defense=20, life=15),
       resistances=res(fire=10, cold=10)),
     "Plain grey wool that turns aside the cold."),
    ("blinkbat-form", "Blinkbat's Form", "chest", 12,
     s(statMods=sm(defense=30, attackSpeed=10), resistances=res(fire=15)),
     "Stitched of bat-leather; quick and silent."),
    ("the-centurion", "The Centurion", "chest", 14,
     s(coreStats=cs(strength=10, vitality=10), statMods=sm(defense=40)),
     "An old soldier's mail, well-traveled."),
    ("twitchthroe", "Twitchthroe", "chest", 16,
     s(coreStats=cs(strength=8, dexterity=8), statMods=sm(defense=40, attackSpeed=20)),
     "Restless armor that fidgets in battle."),
    ("darkglow", "Darkglow", "chest", 20,
     s(statMods=sm(defense=60), resistances=res(fire=15, cold=15, lightning=15, poison=15, arcane=15)),
     "It glimmers with a strange, soft light."),
    ("hawkmail", "Hawkmail", "chest", 19,
     s(coreStats=cs(dexterity=10), statMods=sm(defense=50), resistances=res(cold=20)),
     "Light scales, swift as a hawk."),
    ("sparking-mail", "Sparking Mail", "chest", 23,
     s(statMods=sm(defense=60), resistances=res(lightning=30)),
     "Static crackles between every link."),
    ("venom-ward", "Venom Ward", "chest", 26,
     s(statMods=sm(defense=70), resistances=res(poison=50)),
     "Steeped in antitoxins by a desert druid."),
    ("iceblink", "Iceblink", "chest", 22,
     s(statMods=sm(defense=70), resistances=res(cold=30)),
     "Frosted plate that numbs an attacker's grip."),
    ("heavenly-garb", "Heavenly Garb", "chest", 24,
     s(coreStats=cs(energy=10), statMods=sm(defense=50, mana=40),
       resistances=res(arcane=15)),
     "A robe spun from sunset cloth."),
    ("rockfleece", "Rockfleece", "chest", 31,
     s(coreStats=cs(strength=15), statMods=sm(defense=120)),
     "Granite-fiber wool. Heavy but indestructible."),
    ("boneflesh", "Boneflesh", "chest", 28,
     s(coreStats=cs(strength=10), statMods=sm(defense=80, life=30)),
     "A grim coat of bone-plates lashed with sinew."),
    ("rattlecage", "Rattlecage", "chest", 29,
     s(coreStats=cs(strength=10), statMods=sm(defense=90, attack=60)),
     "Skull-charms clatter as you move."),
    ("goldskin", "Goldskin", "chest", 36,
     s(statMods=sm(defense=130, goldFind=100, magicFind=25)),
     "Gilded with the sweat of a covetous king."),
    ("silks-of-the-victor", "Silks of the Victor", "chest", 28,
     s(coreStats=cs(strength=10), statMods=sm(defense=80, mana=20)),
     "Worn by champions of the arena."),
    ("the-spirit-shroud", "The Spirit Shroud", "chest", 28,
     s(coreStats=cs(energy=5), statMods=sm(defense=80, mana=40)),
     "A whisper-thin robe haunted by past wearers."),
    ("skin-of-flayed-one", "Skin of the Flayed One", "chest", 31,
     s(coreStats=cs(vitality=15), statMods=sm(defense=100, life=50)),
     "It still twitches when blood is shed near it."),
    ("iron-pelt", "Iron Pelt", "chest", 33,
     s(coreStats=cs(strength=20), statMods=sm(defense=140)),
     "A tribe-chief's plate, banded in cold iron."),
    ("crow-caw", "Crow Caw", "chest", 36,
     s(coreStats=cs(dexterity=15), statMods=sm(defense=110, attackSpeed=20)),
     "Black feathers fan out at every sudden move."),
    ("spirit-forge", "Spirit Forge", "chest", 49,
     s(coreStats=cs(strength=15, vitality=10), statMods=sm(defense=160, life=50)),
     "Quenched in the tears of a battle-spirit."),
    ("shaftstop", "Shaftstop", "chest", 38,
     s(coreStats=cs(vitality=10), statMods=sm(defense=180, life=60),
       resistances=res(physical=10)),
     "Shrugs off arrows like raindrops."),
    ("black-hades", "Black Hades", "chest", 53,
     s(coreStats=cs(strength=15), statMods=sm(defense=200),
       resistances=res(fire=25)),
     "Forged in the cold black heart of a volcano."),
    ("corpsemourn", "Corpsemourn", "chest", 55,
     s(coreStats=cs(vitality=15), statMods=sm(defense=180, life=70),
       resistances=res(poison=30)),
     "It weeps for the dead it has carried into battle."),
    ("ormus-robes", "Ormus' Robes", "chest", 75,
     s(coreStats=cs(energy=15), statMods=sm(defense=140, mana=80),
       resistances=res(arcane=25)),
     "The mage Ormus' own working-robes."),
    ("the-gladiator-bane", "The Gladiator's Bane", "chest", 85,
     s(coreStats=cs(strength=20, vitality=20), statMods=sm(defense=250, life=80, magicDodge=15)),
     "Worn into countless arenas. None of its foes survived."),
    ("templar-might", "Templar's Might", "chest", 74,
     s(coreStats=cs(strength=25, vitality=20), statMods=sm(defense=240, attack=100)),
     "The breastplate of a holy crusader."),
    ("steel-carapace", "Steel Carapace", "chest", 65,
     s(coreStats=cs(strength=20), statMods=sm(defense=220),
       resistances=res(physical=15)),
     "An insectoid plate of overlapping steel."),

    # ============== GLOVES ==============
    ("hand-of-broc", "The Hand of Broc", "gloves", 5,
     s(statMods=sm(defense=10, life=10, mana=10), resistances=res(poison=15)),
     "Calloused leather that drinks poison harmlessly."),
    ("chance-guards", "Chance Guards", "gloves", 15,
     s(statMods=sm(magicFind=40, goldFind=200, defense=20)),
     "Thieves' gloves — fortune just sticks to them."),
    ("venom-grip", "Venom Grip", "gloves", 29,
     s(statMods=sm(defense=30, life=20), resistances=res(poison=25)),
     "Snakeskin gauntlets that drip with venom."),
    ("gravepalm", "Gravepalm", "gloves", 38,
     s(coreStats=cs(strength=10), statMods=sm(defense=40, attack=40)),
     "Necromantic gloves — your touch withers the living."),
    ("ghoulhide", "Ghoulhide", "gloves", 47,
     s(coreStats=cs(strength=15), statMods=sm(defense=50, attack=60),
       resistances=res(poison=20)),
     "Stripped from a ghoul-king. They still hunger."),
    ("hellmouth", "Hellmouth", "gloves", 61,
     s(coreStats=cs(strength=15), statMods=sm(defense=60, attackSpeed=20),
       resistances=res(fire=30), damageBonus=dmg(0, 30, fire=30)),
     "Tongues of flame lick from every fingertip."),

    # ============== BOOTS ==============
    ("gorefoot", "Gorefoot", "boots", 9,
     s(statMods=sm(defense=15, attackSpeed=10), resistances=res(fire=10)),
     "Bloodstained boots that quicken every stride."),
    ("treads-of-cthon", "Treads of Cthon", "boots", 15,
     s(coreStats=cs(strength=5), statMods=sm(defense=30, life=20)),
     "Leaves no print, no matter the soil."),
    ("goblin-toe", "Goblin Toe", "boots", 22,
     s(statMods=sm(defense=30, critChance=15)),
     "Squashed-tip boots, oddly sturdy."),
    ("tearhaunch", "Tearhaunch", "boots", 29,
     s(coreStats=cs(strength=5, dexterity=5), statMods=sm(defense=40, attackSpeed=15)),
     "A pilgrim's worn boots — quick and tireless."),
    ("infernostride", "Infernostride", "boots", 49,
     s(statMods=sm(defense=60, life=20), resistances=res(fire=30)),
     "Each step leaves a cinder smoldering."),
    ("waterwalk", "Waterwalk", "boots", 49,
     s(coreStats=cs(dexterity=15), statMods=sm(defense=60, life=40),
       resistances=res(fire=20)),
     "They glide over water as easily as land."),
    ("shadow-dancer", "Shadow Dancer", "boots", 71,
     s(coreStats=cs(dexterity=20), statMods=sm(defense=80, magicDodge=15)),
     "An assassin's boots — soundless, weightless."),

    # ============== BELTS ==============
    ("lenymo", "Lenymo", "belt", 7,
     s(statMods=sm(mana=30, defense=10), resistances=res(arcane=15)),
     "A spellweaver's sash, threaded with mana."),
    ("snakecord", "Snakecord", "belt", 12,
     s(statMods=sm(defense=20, life=15), resistances=res(poison=25)),
     "A live serpent draped at the waist — calmed by old magic."),
    ("nightsmoke", "Nightsmoke", "belt", 20,
     s(statMods=sm(defense=30, mana=30), resistances=res(arcane=20)),
     "It smolders faintly in the dark."),
    ("goldwrap", "Goldwrap", "belt", 27,
     s(statMods=sm(defense=40, goldFind=80, magicFind=30)),
     "A merchant-prince's gilded sash."),
    ("bladebuckle", "Bladebuckle", "belt", 39,
     s(coreStats=cs(strength=15), statMods=sm(defense=80, attack=60)),
     "Razor-sharp buckle — cuts grasping hands."),
    ("snowclash", "Snowclash", "belt", 55,
     s(coreStats=cs(strength=10), statMods=sm(defense=80),
       resistances=res(cold=40)),
     "A glacier-forged belt that radiates a chill."),
    ("gloom-trap", "Gloom's Trap", "belt", 36,
     s(coreStats=cs(energy=15), statMods=sm(mana=80, defense=50)),
     "A scholar's sash — knowledge weighs heavy."),
    ("nosferatu-coil", "Nosferatu's Coil", "belt", 51,
     s(coreStats=cs(strength=15), statMods=sm(defense=60, attackSpeed=10, life=20)),
     "A vampire-lord's belt — drains the unwary."),

    # ============== RINGS ==============
    ("dwarf-star", "Dwarf Star", "ring", 45,
     s(statMods=sm(life=40, defense=20), resistances=res(fire=40)),
     "A tiny ruby cut by dwarven hands."),
    ("wisp-projector", "Wisp Projector", "ring", 76,
     s(statMods=sm(magicFind=15), resistances=res(lightning=20)),
     "Dancing wisps swirl around the wearer."),

    # ============== AMULETS ==============
    ("nokozan-relic", "Nokozan Relic", "amulet", 16,
     s(statMods=sm(life=20), resistances=res(fire=25), damageBonus=dmg(1, 6, fire=6)),
     "A relic from a long-buried fire-temple."),
    ("eye-of-etlich", "The Eye of Etlich", "amulet", 15,
     s(statMods=sm(defense=20, life=15), resistances=res(cold=15)),
     "A pale gem that watches from the wearer's chest."),
    ("mahim-oak-curio", "The Mahim-Oak Curio", "amulet", 25,
     s(coreStats=cs(strength=10, dexterity=10, vitality=10, energy=10), statMods=sm(defense=20)),
     "A curio whittled from a holy oak."),
    ("saracen-chance", "Saracen's Chance", "amulet", 37,
     s(coreStats=cs(strength=12, dexterity=12, vitality=12, energy=12), statMods=sm(magicFind=25)),
     "A desert wanderer's lucky charm."),
    ("cat-eye", "The Cat's Eye", "amulet", 50,
     s(coreStats=cs(dexterity=25), statMods=sm(attackSpeed=20, defense=30)),
     "A feline gem — sharp eyes, swift paws."),
    ("rising-sun", "The Rising Sun", "amulet", 65,
     s(statMods=sm(defense=30), resistances=res(fire=30), damageBonus=dmg(8, 16, fire=16)),
     "A sun-warm pendant. Demons burn at its glow."),
    ("crescent-moon", "Crescent Moon", "amulet", 50,
     s(statMods=sm(mana=30), resistances=res(lightning=30), damageBonus=dmg(3, 9, lightning=9)),
     "Curved silver, charged with thunder."),
    ("metalgrid", "Metalgrid", "amulet", 81,
     s(statMods=sm(defense=200, attack=100),
       resistances=res(fire=25, cold=25, lightning=25, poison=25)),
     "An iron lattice — pure structure and protection."),

    # ============== SHIELDS ==============
    ("pelta-lunata", "Pelta Lunata", "shield", 2,
     s(statMods=sm(defense=20, life=10)),
     "A crescent-moon buckler from the Skovos Isles."),
    ("umbral-disk", "Umbral Disk", "shield", 14,
     s(statMods=sm(defense=40), resistances=res(arcane=20)),
     "A shadow-forged disk — magic glances aside."),
    ("stormguild", "Stormguild", "shield", 23,
     s(statMods=sm(defense=60), resistances=res(lightning=30)),
     "A guildsmen's mark, charged with storm."),
    ("steelclash", "Steelclash", "shield", 42,
     s(statMods=sm(defense=120),
       resistances=res(fire=20, cold=20, lightning=20)),
     "Rings like a bell when struck."),
    ("tiamat-rebuke", "Tiamat's Rebuke", "shield", 55,
     s(statMods=sm(defense=160),
       resistances=res(fire=25, cold=25, lightning=25)),
     "A dragon's hide stretched on a great frame."),
    ("visceratuant", "Visceratuant", "shield", 28,
     s(coreStats=cs(energy=10), statMods=sm(defense=70, mana=40)),
     "A spell-shield carved with binding glyphs."),
    ("wall-of-eyeless", "Wall of the Eyeless", "shield", 20,
     s(coreStats=cs(energy=8), statMods=sm(defense=50, mana=30)),
     "A dark mirror that watches back."),
    ("bverrit-keep", "Bverrit Keep", "shield", 45,
     s(coreStats=cs(strength=10), statMods=sm(defense=140),
       resistances=res(fire=30)),
     "A keep-shaped tower shield, fire-tempered."),
    ("spike-thorn", "Spike Thorn", "shield", 58,
     s(coreStats=cs(strength=15), statMods=sm(defense=160),
       resistances=res(physical=10)),
     "Bristling iron thorns punish the bold."),
    ("head-hunter-glory", "Head Hunter's Glory", "shield", 75,
     s(coreStats=cs(strength=20, vitality=10), statMods=sm(defense=200, life=80)),
     "Trophy-skulls of slain champions adorn its rim."),
    ("radament-sphere", "Radament's Sphere", "shield", 60,
     s(coreStats=cs(strength=15, energy=15), statMods=sm(defense=170, mana=60),
       resistances=res(poison=30)),
     "A mummified scarab-mage's funerary disk."),
    ("stormchaser", "Stormchaser", "shield", 21,
     s(statMods=sm(defense=50), resistances=res(lightning=40),
       damageBonus=dmg(1, 12, lightning=12)),
     "Lightning leaps from its rim to strike attackers."),
    ("atlantean", "The Atlantean", "shield", 50,
     s(coreStats=cs(strength=15, vitality=10), statMods=sm(defense=160),
       resistances=res(cold=30)),
     "Salt-eaten plate from a sunken empire."),

    # ============== 1H SWORDS ==============
    ("rixots-keen", "Rixot's Keen", "sword1h", 2,
     s(statMods=sm(attack=40), damageBonus=dmg(1, 2, physical=2)),
     "A simple short sword, kept impossibly sharp."),
    ("blood-crescent", "Blood Crescent", "sword1h", 7,
     s(statMods=sm(attackSpeed=15, attack=50, life=15)),
     "A curved blade that drinks deep."),
    ("skewer-of-krintiz", "Skewer of Krintiz", "sword1h", 9,
     s(statMods=sm(attack=70), damageBonus=dmg(2, 6, physical=6)),
     "A thin, vicious thrusting blade."),
    ("gleamscythe", "Gleamscythe", "sword1h", 13,
     s(statMods=sm(attack=60, attackSpeed=20)),
     "A scimitar polished to a moonlight gleam."),
    ("griswold-edge", "Griswold's Edge", "sword1h", 15,
     s(statMods=sm(attack=80, attackSpeed=20),
       damageBonus=dmg(1, 12, fire=12)),
     "The blacksmith of Tristram's signature blade."),
    ("hellplague", "Hellplague", "sword1h", 25,
     s(statMods=sm(attack=110),
       damageBonus=dmg(8, 16, fire=8, poison=8)),
     "A blade that fester wounds with every cut."),
    ("culwens-point", "Culwen's Point", "sword1h", 31,
     s(statMods=sm(attack=130, attackSpeed=20)),
     "A smith's masterpiece — perfectly balanced."),
    ("shadowfang", "Shadowfang", "sword1h", 12,
     s(statMods=sm(attack=70, attackSpeed=10),
       damageBonus=dmg(3, 6, cold=6)),
     "A cold blade carved from frost-iron."),
    ("soulflay", "Soulflay", "sword1h", 22,
     s(statMods=sm(attack=120),
       damageBonus=dmg(5, 10, arcane=10)),
     "It severs more than flesh."),
    ("kinemil-awl", "Kinemil's Awl", "sword1h", 32,
     s(statMods=sm(attack=140),
       damageBonus=dmg(10, 20, fire=20)),
     "A red-hot point that never cools."),
    ("blacktongue", "Blacktongue", "sword1h", 35,
     s(statMods=sm(attack=140),
       damageBonus=dmg(10, 20, poison=20)),
     "A tongue-shaped blade, drips with venom."),
    ("ripsaw", "Ripsaw", "sword1h", 36,
     s(statMods=sm(attack=160, attackSpeed=20),
       damageBonus=dmg(15, 25, physical=25)),
     "Toothed iron — it tears flesh into ribbons."),
    ("the-patriarch", "The Patriarch", "sword1h", 39,
     s(coreStats=cs(strength=20), statMods=sm(attack=160),
       damageBonus=dmg(15, 30, physical=30)),
     "A clan-elder's sword, wisdom in steel."),
    ("the-vile-husk", "The Vile Husk", "sword1h", 38,
     s(statMods=sm(attack=140),
       damageBonus=dmg(12, 22, poison=22), resistances=res(poison=20)),
     "A hollow, husk-light blade humming with poison."),
    ("djinn-slayer", "Djinn Slayer", "sword1h", 65,
     s(statMods=sm(attack=190, attackSpeed=30),
       damageBonus=dmg(50, 80, fire=80)),
     "A scimitar tempered in genie-fire."),
    ("the-atlantean", "The Atlantean Sword", "sword1h", 40,
     s(coreStats=cs(strength=15, vitality=10), statMods=sm(attack=170),
       damageBonus=dmg(20, 40, physical=40)),
     "A sword of the drowned legions."),
    ("blade-of-ali-baba", "Blade of Ali Baba", "sword1h", 35,
     s(statMods=sm(attack=120, magicFind=25, goldFind=200)),
     "A thief's blade — even the dust turns to coin."),
    ("crainte-vomir", "Crainte Vomir", "sword1h", 50,
     s(statMods=sm(attack=180, attackSpeed=20),
       damageBonus=dmg(30, 50, physical=50)),
     "A baroque blade dripping with menace."),
    ("bing-sz-wang", "Bing Sz Wang", "sword1h", 55,
     s(statMods=sm(attack=180),
       damageBonus=dmg(40, 60, cold=60), resistances=res(cold=30)),
     "Frosted katana — its edge never melts."),
    ("the-vile-husk-2", "The Vile Husk II", "sword1h", 60,
     s(statMods=sm(attack=200), damageBonus=dmg(40, 60, poison=60)),
     "A second blade of the same accursed lineage."),
    ("plague-bearer", "Plague Bearer", "sword1h", 68,
     s(statMods=sm(attack=200),
       damageBonus=dmg(30, 60, poison=60), resistances=res(poison=40)),
     "A sword that brings a withering rot."),
    ("the-cranium-basher", "The Cranium Basher", "mace", 87,
     s(coreStats=cs(strength=35), statMods=sm(attack=300, critChance=20),
       damageBonus=dmg(150, 240, physical=240)),
     "It does what its name suggests."),

    # ============== 2H WEAPONS ==============
    ("the-meatscraper", "The Meat Scraper", "sword2h", 36,
     s(statMods=sm(attack=160), damageBonus=dmg(20, 40, physical=40)),
     "A butcher's blade — meant for unfair fights."),
    ("blackleach-blade", "Blackleach Blade", "sword2h", 38,
     s(statMods=sm(attack=180, life=30),
       damageBonus=dmg(30, 50, physical=50)),
     "A leech-shaped blade that drinks blood."),
    ("athulua-rule", "Athulua's Rule", "sword2h", 60,
     s(statMods=sm(attack=220),
       damageBonus=dmg(60, 100, physical=100)),
     "An ancient queen's two-handed scepter."),
    ("the-impaler", "The Impaler", "sword2h", 31,
     s(statMods=sm(attack=160), damageBonus=dmg(30, 50, physical=50)),
     "A spiked pike that runs foes through."),
    ("kelpie-snare", "Kelpie Snare", "sword2h", 33,
     s(statMods=sm(attack=170),
       damageBonus=dmg(20, 40, cold=40), resistances=res(cold=20)),
     "A jagged hook from the cold deeps."),
    ("hone-sundan", "Hone Sundan", "sword2h", 37,
     s(statMods=sm(attack=200, critChance=10),
       damageBonus=dmg(40, 70, physical=70)),
     "A bone-shaped polearm, brittle-looking but deadly."),
    ("spire-of-honor", "Spire of Honor", "sword2h", 41,
     s(statMods=sm(attack=210),
       damageBonus=dmg(50, 90, physical=90)),
     "A polearm tipped with a paladin's signet."),
    ("the-battlebranch", "The Battlebranch", "sword2h", 53,
     s(coreStats=cs(strength=15), statMods=sm(attack=230),
       damageBonus=dmg(60, 100, physical=100)),
     "A young oak hewn into a war-pole."),
    ("woestave", "Woestave", "sword2h", 50,
     s(statMods=sm(attack=200),
       damageBonus=dmg(50, 80, cold=40, lightning=40)),
     "A staff of layered curses."),
    ("messerschmidt-reaver", "Messerschmidt's Reaver", "sword2h", 84,
     s(coreStats=cs(strength=30), statMods=sm(attack=280),
       damageBonus=dmg(150, 250, physical=250)),
     "A masterwork two-hander of staggering reach."),
    ("steel-pillar", "Steel Pillar", "sword2h", 65,
     s(coreStats=cs(strength=25), statMods=sm(attack=240),
       damageBonus=dmg(80, 130, physical=130)),
     "It's less a weapon and more a column."),
    ("the-grim-reaper", "The Grim Reaper", "sword2h", 70,
     s(statMods=sm(attack=260),
       damageBonus=dmg(100, 160, physical=160)),
     "A scythe that ushers souls to oblivion."),

    # ============== AXES ==============
    ("the-gnasher", "The Gnasher", "axe", 5,
     s(statMods=sm(attack=50, attackSpeed=15),
       damageBonus=dmg(2, 6, physical=6)),
     "A small axe with a vicious bite."),
    ("deathspade", "Deathspade", "axe", 9,
     s(statMods=sm(attack=70),
       damageBonus=dmg(4, 10, physical=10)),
     "A spade-headed hatchet, dull but heavy."),
    ("bloodrise", "Bloodrise", "axe", 15,
     s(statMods=sm(attack=80, attackSpeed=10),
       damageBonus=dmg(6, 12, physical=12)),
     "It seems to grow heavier with every kill."),
    ("the-general-tan-do-li-ga", "The General's Tan Do Li Ga", "axe", 21,
     s(coreStats=cs(strength=10), statMods=sm(attack=100),
       damageBonus=dmg(10, 20, physical=20)),
     "A general's heirloom — well-traveled, well-bloodied."),
    ("ichorsting", "Ichorsting", "axe", 27,
     s(statMods=sm(attack=110),
       damageBonus=dmg(8, 16, poison=16)),
     "A barbed axe — wounds fester for days."),
    ("razor-tine", "Razor's Tine", "axe", 33,
     s(coreStats=cs(dexterity=10), statMods=sm(attack=130, critChance=10),
       damageBonus=dmg(15, 30, physical=30)),
     "A vicious bearded axe with a hair-thin edge."),
    ("coldkill", "Coldkill", "axe", 37,
     s(statMods=sm(attack=140),
       damageBonus=dmg(20, 40, cold=40), resistances=res(cold=20)),
     "An axe of permanent winter."),
    ("butcher-pupil", "Butcher's Pupil", "axe", 39,
     s(statMods=sm(attack=160, attackSpeed=20),
       damageBonus=dmg(30, 50, physical=50)),
     "A meat-cleaver as taught by the Butcher of Tristram."),
    ("islestrike", "Islestrike", "axe", 49,
     s(statMods=sm(attack=170),
       damageBonus=dmg(40, 70, physical=70)),
     "An island-crusher's axe."),
    ("pompe-wrath", "Pompeii's Wrath", "axe", 56,
     s(statMods=sm(attack=180),
       damageBonus=dmg(40, 80, fire=80), resistances=res(fire=30)),
     "Tempered in volcanic ash."),
    ("guardian-naga", "Guardian Naga", "axe", 58,
     s(statMods=sm(attack=180),
       damageBonus=dmg(40, 70, poison=70), resistances=res(poison=30)),
     "Snake-engraved haft, venom-edged."),
    ("warlord-trust", "Warlord's Trust", "axe", 64,
     s(coreStats=cs(strength=20), statMods=sm(attack=200),
       damageBonus=dmg(60, 100, physical=100)),
     "A trusted lieutenant's reward."),
    ("spellsteel", "Spellsteel", "axe", 67,
     s(coreStats=cs(energy=15), statMods=sm(attack=180, mana=60),
       damageBonus=dmg(40, 70, arcane=70)),
     "Sigils glow on its haft when foes near."),
    ("stormrider", "Stormrider", "axe", 70,
     s(statMods=sm(attack=210),
       damageBonus=dmg(50, 90, lightning=90)),
     "Wielded by a storm-knight of the Skovos."),
    ("boneslayer-blade", "Boneslayer Blade", "axe", 75,
     s(coreStats=cs(strength=25), statMods=sm(attack=230),
       damageBonus=dmg(80, 130, physical=130)),
     "Carves through bone like soft wood."),
    ("the-minotaur", "The Minotaur", "axe", 80,
     s(coreStats=cs(strength=30, vitality=15), statMods=sm(attack=250),
       damageBonus=dmg(100, 160, physical=160)),
     "An axe of the labyrinth's lord."),
    ("ethereal-edge", "Ethereal Edge", "axe", 85,
     s(coreStats=cs(strength=25, dexterity=15), statMods=sm(attack=260, attackSpeed=20),
       damageBonus=dmg(120, 180, physical=180)),
     "A blade glimpsed half in this world, half in another."),

    # ============== MACES & SCEPTERS ==============
    ("felloak", "Felloak", "mace", 7,
     s(statMods=sm(attack=60),
       damageBonus=dmg(3, 8, fire=8)),
     "A burning club of charred oak."),
    ("stoutnail", "Stoutnail", "mace", 10,
     s(statMods=sm(attack=70, defense=20),
       damageBonus=dmg(5, 10, physical=10)),
     "A simple iron-banded club. Reliable."),
    ("crushflange", "Crushflange", "mace", 14,
     s(statMods=sm(attack=80, critChance=10),
       damageBonus=dmg(6, 14, physical=14)),
     "A flanged mace that pulps any armor."),
    ("bloodrise-2", "Bloodrise (Mace)", "mace", 16,
     s(statMods=sm(attack=90),
       damageBonus=dmg(6, 14, physical=14)),
     "A heavy bloodied club, well-used."),
    ("the-general-mace", "The Generals' Mace", "mace", 21,
     s(coreStats=cs(strength=10), statMods=sm(attack=100),
       damageBonus=dmg(10, 20, physical=20)),
     "A general's flail-mace, parade-polished."),
    ("ironstone", "Ironstone", "mace", 28,
     s(coreStats=cs(strength=10), statMods=sm(attack=110),
       damageBonus=dmg(15, 25, physical=25)),
     "Stone-headed, iron-banded — primitive but lethal."),
    ("dark-clan-crusher", "Dark Clan Crusher", "mace", 32,
     s(statMods=sm(attack=130),
       damageBonus=dmg(20, 35, physical=35)),
     "A clan-mace blackened with old soot."),
    ("knell-striker", "Knell Striker", "mace", 36,
     s(statMods=sm(attack=140),
       damageBonus=dmg(25, 40, physical=40)),
     "Strikes a sour, ringing toll."),
    ("rusthandle", "Rusthandle", "mace", 41,
     s(statMods=sm(attack=150),
       damageBonus=dmg(30, 50, physical=50)),
     "Looks ruined, hits like a falling tower."),
    ("stormeye", "Stormeye", "mace", 50,
     s(statMods=sm(attack=170),
       damageBonus=dmg(30, 60, lightning=60)),
     "A storm-spawned warhammer."),
    ("nords-tenderizer", "Nord's Tenderizer", "mace", 68,
     s(coreStats=cs(strength=25), statMods=sm(attack=210),
       damageBonus=dmg(60, 100, physical=100)),
     "A flailing meat-mallet from the icebound north."),
    ("demon-limb", "Demon Limb", "mace", 63,
     s(statMods=sm(attack=200),
       damageBonus=dmg(50, 90, fire=90), resistances=res(fire=30)),
     "Ripped from a fallen pit lord."),
    ("earthshifter", "Earthshifter", "mace", 69,
     s(coreStats=cs(strength=20), statMods=sm(attack=200),
       damageBonus=dmg(70, 100, physical=100)),
     "A maul that cracks stone underfoot."),
    ("knell-striker-2", "Knell Striker (Greater)", "mace", 78,
     s(statMods=sm(attack=240),
       damageBonus=dmg(80, 120, physical=120)),
     "Tolls the death-knell with every swing."),
    # Scepters
    ("rusthandle-scepter", "Rusty Scepter", "scepter", 17,
     s(statMods=sm(attack=70),
       damageBonus=dmg(5, 10, physical=10)),
     "A holy scepter, neglected but still potent."),
    ("knell-striker-scepter", "Striking Sigil", "scepter", 22,
     s(statMods=sm(attack=90),
       damageBonus=dmg(10, 20, arcane=20)),
     "Glyph-engraved scepter — strikes both flesh and faith."),
    ("the-fetid-sprinkler", "The Fetid Sprinkler", "scepter", 29,
     s(statMods=sm(attack=120),
       damageBonus=dmg(20, 30, poison=30), resistances=res(poison=20)),
     "A clergy's foul-water sprinkler — repurposed."),
    ("hand-of-blessed-light", "Hand of Blessed Light", "scepter", 79,
     s(coreStats=cs(strength=20, energy=15), statMods=sm(attack=240),
       damageBonus=dmg(80, 130, arcane=130)),
     "A holy mace radiating sun-warm light."),

    # ============== POLEARMS / SPEARS ==============
    ("the-dragon-chang", "The Dragon Chang", "polearm", 17,
     s(statMods=sm(attack=110),
       damageBonus=dmg(10, 20, fire=20)),
     "A spear-tip wreathed in lazy flame."),
    ("razor-stitch", "Razortail Pike", "polearm", 25,
     s(coreStats=cs(dexterity=10), statMods=sm(attack=120),
       damageBonus=dmg(15, 30, physical=30)),
     "A barbed pike — leaves a wound that never closes."),
    ("bonehew", "Bonehew", "polearm", 64,
     s(coreStats=cs(strength=20), statMods=sm(attack=200),
       damageBonus=dmg(60, 100, physical=100)),
     "A bone-haft polearm — fast, vicious."),
    ("pierre-tombale-couant", "Pierre Tombale Couant", "polearm", 50,
     s(statMods=sm(attack=180),
       damageBonus=dmg(40, 70, physical=70)),
     "A grave-marker-shaped halberd."),
    ("the-meat-scraper-2", "The Meat Scraper (Pole)", "polearm", 39,
     s(statMods=sm(attack=160),
       damageBonus=dmg(30, 50, physical=50)),
     "A bladed pole that scrapes corpses clean."),
    ("blackleach-staff", "Blackleach (Staff)", "polearm", 38,
     s(statMods=sm(attack=170, life=20),
       damageBonus=dmg(20, 40, physical=40)),
     "A leech-shaped polearm draining the unwary."),

    # ============== BOWS / CROSSBOWS ==============
    ("pluckeye", "Pluckeye", "bow", 7,
     s(statMods=sm(attack=60, attackSpeed=15),
       damageBonus=dmg(3, 6, physical=6)),
     "A keen-eyed hunter's first bow."),
    ("witherstring", "Witherstring", "bow", 13,
     s(statMods=sm(attack=80),
       damageBonus=dmg(5, 12, physical=12)),
     "Its string is sinew — strong and sour."),
    ("rasperose", "Raven Claw", "bow", 15,
     s(statMods=sm(attack=90, attackSpeed=20),
       damageBonus=dmg(6, 14, physical=14)),
     "A raven's claw nocks each arrow."),
    ("rogue-bow", "Rogue's Bow", "bow", 20,
     s(coreStats=cs(dexterity=10), statMods=sm(attack=110, attackSpeed=20),
       damageBonus=dmg(10, 20, physical=20)),
     "A scout-rogue's well-tested longbow."),
    ("stormstrike", "Stormstrike", "bow", 25,
     s(statMods=sm(attack=120),
       damageBonus=dmg(10, 20, lightning=20)),
     "Each loosed arrow crackles with thunder."),
    ("wizendraw", "Wizendraw", "bow", 26,
     s(coreStats=cs(dexterity=10), statMods=sm(attack=130),
       damageBonus=dmg(15, 25, cold=25)),
     "An ancient bow — its string never warps."),
    ("hellclap", "Hellclap", "bow", 27,
     s(statMods=sm(attack=130, attackSpeed=20),
       damageBonus=dmg(20, 30, fire=30)),
     "Each arrow bursts on impact."),
    ("blastbark", "Blastbark", "bow", 35,
     s(statMods=sm(attack=150),
       damageBonus=dmg(25, 40, fire=40)),
     "A bark-yew bow that shatters wards."),
    ("skystrike", "Skystrike", "bow", 35,
     s(coreStats=cs(dexterity=15), statMods=sm(attack=160),
       damageBonus=dmg(30, 50, lightning=50)),
     "An archer-king's bow — calls down lightning."),
    ("riphook", "Riphook", "bow", 31,
     s(statMods=sm(attack=140),
       damageBonus=dmg(25, 40, physical=40)),
     "Hooked-tip arrows that tear on withdrawal."),
    ("kuko-shakaku", "Kuko Shakaku", "bow", 47,
     s(coreStats=cs(dexterity=20), statMods=sm(attack=180, attackSpeed=30),
       damageBonus=dmg(40, 70, physical=70)),
     "A swift Skovos longbow."),
    ("endlesshail", "Endlesshail", "bow", 55,
     s(statMods=sm(attack=200, attackSpeed=20),
       damageBonus=dmg(50, 80, cold=80)),
     "Looses arrows in a frozen rain."),
    ("widowmaker", "Widowmaker", "bow", 65,
     s(coreStats=cs(dexterity=25), statMods=sm(attack=220),
       damageBonus=dmg(70, 110, physical=110)),
     "A widow-bow — leaves no husband walking."),
    ("hellrack", "Hellrack", "crossbow", 76,
     s(coreStats=cs(strength=25), statMods=sm(attack=240),
       damageBonus=dmg(80, 130, fire=130)),
     "A demonic crossbow that fires hellfire."),
    ("doomslinger", "Doomslinger", "crossbow", 18,
     s(statMods=sm(attack=110),
       damageBonus=dmg(10, 20, physical=20)),
     "An apprentice's first crossbow — surprisingly potent."),
    ("langer-briser", "Langer Briser", "crossbow", 35,
     s(statMods=sm(attack=160),
       damageBonus=dmg(30, 50, physical=50)),
     "An old siege-bow, repurposed."),
    ("pus-spitter", "Pus Spitter", "crossbow", 45,
     s(statMods=sm(attack=170),
       damageBonus=dmg(30, 50, poison=50)),
     "Bolts dipped in foul ichor."),
    ("buriza-do-kyanon-cb", "Buriza-Do Kyanon (Crossbow)", "crossbow", 55,
     s(statMods=sm(attack=190, attackSpeed=30),
       damageBonus=dmg(40, 70, cold=70)),
     "An ice-bolt crossbow of devastating reach."),

    # ============== WANDS / ORBS (mapped to wand) ==============
    ("torch-of-iros", "Torch of Iro", "wand", 6,
     s(coreStats=cs(energy=5), statMods=sm(attack=30, mana=20),
       damageBonus=dmg(2, 6, fire=6)),
     "A wand that always burns at the tip."),
    ("maelstrom", "Maelstrom", "wand", 18,
     s(coreStats=cs(energy=8), statMods=sm(attack=50, mana=30),
       damageBonus=dmg(5, 12, lightning=12)),
     "A spiraling rod that hums with storm."),
    ("gravenspine", "Gravenspine", "wand", 25,
     s(coreStats=cs(energy=10), statMods=sm(attack=70, mana=40),
       damageBonus=dmg(8, 16, arcane=16)),
     "Carved from the spine of a long-dead lich."),
    ("ume-lament", "Ume's Lament", "wand", 30,
     s(coreStats=cs(energy=15), statMods=sm(attack=80, mana=60),
       damageBonus=dmg(10, 20, arcane=20)),
     "A widow's wand — it weeps for the dead."),
    ("suicide-branch", "Suicide Branch", "wand", 60,
     s(coreStats=cs(energy=20), statMods=sm(mana=80),
       damageBonus=dmg(20, 40, arcane=40)),
     "A withered branch that pleads to be broken."),
    ("carin-shard", "Carin Shard", "wand", 65,
     s(coreStats=cs(energy=20), statMods=sm(mana=100, defense=40),
       damageBonus=dmg(20, 40, arcane=40)),
     "A wand of bound spirit-glass."),

    # ============== Class-specific (closest-fit base) ==============
    # Druid pelts → helm
    ("cerebus-bite", "Cerebus' Bite", "helm", 67,
     s(coreStats=cs(strength=15), statMods=sm(defense=110, attack=80)),
     "A three-headed wolf-pelt for a druid."),
    ("ravenlore", "Ravenlore", "helm", 74,
     s(coreStats=cs(energy=20), statMods=sm(defense=110, mana=60)),
     "A raven-spirit headdress, learned and dark."),
    ("spirit-keeper", "Spirit Keeper", "helm", 75,
     s(coreStats=cs(energy=15), statMods=sm(defense=110, life=40, mana=40)),
     "Holds the spirits of fallen druid elders."),
    ("jalal-mane", "Jalal's Mane", "helm", 42,
     s(coreStats=cs(strength=15, dexterity=10), statMods=sm(defense=80, life=30)),
     "Lion-mane druid pelt, fierce and noble."),
    # Necro shrunken heads → helm
    ("homunculus-helm", "Homunculus (Head)", "helm", 50,
     s(coreStats=cs(energy=10), statMods=sm(defense=80, mana=60)),
     "A shrunken-head fetish, oddly aware."),
    ("blackhand-key", "Blackhand Key", "helm", 47,
     s(coreStats=cs(energy=10), statMods=sm(mana=80)),
     "A skull-key set into a necromancer's totem."),
    ("darkforce-spawn", "Darkforce Spawn", "helm", 67,
     s(coreStats=cs(strength=10, energy=15), statMods=sm(defense=100, mana=60)),
     "A demon-skull totem, alive with whispers."),
    # Barb helms → helm
    ("arreats-face-uniq", "Arreat's Face (Greater)", "helm", 78,
     s(coreStats=cs(strength=30, dexterity=15), statMods=sm(defense=160, life=100)),
     "A war-mask of greater might. (Closest base mapping.)"),
    ("demonhorn-edge-2", "Demonhorn's Edge (Greater)", "helm", 82,
     s(coreStats=cs(strength=25), statMods=sm(defense=160, attack=100)),
     "A larger demon-horn helm of greater make."),
    ("halaberd-reign-2", "Halaberd's Reign (Greater)", "helm", 84,
     s(coreStats=cs(strength=30), statMods=sm(defense=170)),
     "A barbarian crown of unmatched lineage."),
    # Paladin shields → shield
    ("herald-of-zakarum", "Herald of Zakarum", "shield", 42,
     s(coreStats=cs(strength=20, vitality=10), statMods=sm(defense=130),
       resistances=res(fire=20, cold=20, lightning=20, poison=20)),
     "A paladin's auric shield — radiant gold."),
    ("dragonscale", "Dragonscale", "shield", 67,
     s(coreStats=cs(strength=25), statMods=sm(defense=200),
       resistances=res(fire=40)),
     "A scaled shield from a slain wyrm."),
    ("alma-negra", "Alma Negra", "shield", 77,
     s(coreStats=cs(energy=15, strength=15), statMods=sm(defense=180)),
     "A dark-soul shield bound to its bearer."),
    # Necro shields → shield
    ("darkforce-spawn-shield", "Darkforce Spawn (Shield)", "shield", 67,
     s(coreStats=cs(energy=15), statMods=sm(defense=140, mana=60)),
     "A bone-fetish shield — a necromancer's pride."),
    ("boneflame-shield", "Boneflame Shield", "shield", 79,
     s(coreStats=cs(energy=15), statMods=sm(defense=170, mana=80),
       resistances=res(fire=30)),
     "Skulls along its rim spit cold fire."),
    # Assassin claws → 1h sword
    ("bartuc-cut-throat", "Bartuc's Cut-Throat", "sword1h", 42,
     s(coreStats=cs(dexterity=20), statMods=sm(attack=150, attackSpeed=30),
       damageBonus=dmg(20, 40, physical=40)),
     "A demon-lord's twin claws — quick as thought."),
    ("jade-talon", "Jade Talon", "sword1h", 66,
     s(coreStats=cs(dexterity=20), statMods=sm(attack=200, attackSpeed=40),
       damageBonus=dmg(40, 70, poison=70)),
     "A jade-edged claw — every cut is venom."),
    ("firelizard-talon", "Firelizard's Talons", "sword1h", 62,
     s(coreStats=cs(dexterity=15), statMods=sm(attack=180, attackSpeed=30),
       damageBonus=dmg(40, 70, fire=70)),
     "Lava-lizard claws that scorch the air."),
    ("shadow-killer", "Shadow Killer", "sword1h", 58,
     s(coreStats=cs(dexterity=20), statMods=sm(attack=180, attackSpeed=40),
       damageBonus=dmg(35, 60, physical=60)),
     "An assassin's signature blade — silent and certain."),
    # Amazon javelins/spears → polearm
    ("titan-revenge", "Titan's Revenge", "polearm", 42,
     s(coreStats=cs(strength=20, dexterity=20), statMods=sm(attack=180),
       damageBonus=dmg(40, 80, physical=80)),
     "A javelin that returns to its bearer's hand."),
    ("thunderstroke", "Thunderstroke", "polearm", 69,
     s(statMods=sm(attack=210),
       damageBonus=dmg(60, 100, lightning=100)),
     "A storm-spear from the celestial heights."),
    ("lycanders-aim", "Lycander's Aim", "bow", 42,
     s(coreStats=cs(dexterity=20), statMods=sm(attack=180, attackSpeed=30),
       damageBonus=dmg(40, 70, physical=70)),
     "An Amazon-queen's hunting bow."),
    ("lycanders-flank", "Lycander's Flank", "polearm", 42,
     s(coreStats=cs(strength=15, dexterity=15), statMods=sm(attack=170),
       damageBonus=dmg(40, 70, physical=70)),
     "An Amazon-queen's signature pike."),

    # ============== Misc / LoD-only standouts ==============
    ("steel-shade", "Steel Shade", "helm", 62,
     s(statMods=sm(defense=120, magicDodge=15),
       resistances=res(fire=20, cold=20, lightning=20, poison=20)),
     "A shadowy helm forged of moon-touched steel."),
    ("ondal-wisdom", "Ondal's Wisdom", "wand", 74,
     s(coreStats=cs(energy=25), statMods=sm(mana=100),
       damageBonus=dmg(30, 60, arcane=60)),
     "An archmage's senile wand — still a fount of power."),
    ("the-redeemer", "The Redeemer", "scepter", 62,
     s(coreStats=cs(strength=15, energy=10), statMods=sm(attack=200),
       damageBonus=dmg(60, 100, arcane=100)),
     "A holy scepter that redeems the wicked through fire."),
    ("blackhand-key-2", "Blackhand Key (Greater)", "wand", 69,
     s(coreStats=cs(energy=15), statMods=sm(mana=100, attack=100),
       damageBonus=dmg(40, 80, arcane=80)),
     "A larger key-wand of necromantic make."),
    ("kira-guardian", "Kira's Guardian", "helm", 77,
     s(coreStats=cs(vitality=15), statMods=sm(defense=140, life=80),
       resistances=res(fire=25, cold=25, lightning=25, poison=25, arcane=25)),
     "A guardian-spirit helm — blessed for travelers."),
    ("immortal-king-helm-uniq", "Immortal King Cap (replica)", "helm", 47,
     s(coreStats=cs(strength=15, vitality=10), statMods=sm(defense=110)),
     "A reproduction of an Immortal King's circlet."),

    # ============== Additional batch — daggers/orbs/extra weapons ==============
    ("the-diggler", "The Diggler", "sword1h", 35,
     s(statMods=sm(attack=140, attackSpeed=20),
       damageBonus=dmg(20, 35, physical=35)),
     "A pickaxe-dagger — pries armor open."),
    ("spectral-shard", "Spectral Shard", "sword1h", 25,
     s(coreStats=cs(energy=10), statMods=sm(attack=100, mana=40),
       damageBonus=dmg(10, 20, arcane=20)),
     "A glassy ghost-blade. It cuts through wards."),
    ("jade-tan-do", "The Jade Tan Do", "sword1h", 23,
     s(statMods=sm(attack=110),
       damageBonus=dmg(15, 25, poison=25), resistances=res(poison=25)),
     "A jade-edged dirk for clean, quiet kills."),
    ("black-cleft", "Black Cleft", "sword1h", 27,
     s(statMods=sm(attack=100),
       damageBonus=dmg(10, 20, cold=20)),
     "A jagged blade of frostbitten iron."),
    ("hexfire", "Hexfire", "sword1h", 53,
     s(statMods=sm(attack=180, attackSpeed=30),
       damageBonus=dmg(50, 80, fire=80), resistances=res(fire=30)),
     "A cursed scimitar — fire surges through every cut."),
    ("stoneraven", "Stoneraven", "polearm", 53,
     s(statMods=sm(attack=200),
       damageBonus=dmg(50, 80, physical=80)),
     "A raven-stone polearm hewn by giants."),
    ("the-stone-crusher", "The Stone Crusher", "mace", 73,
     s(coreStats=cs(strength=30), statMods=sm(attack=240, critChance=15),
       damageBonus=dmg(80, 130, physical=130)),
     "A maul that splits boulders open."),
    ("earth-shaker", "Earth Shaker", "mace", 43,
     s(coreStats=cs(strength=20), statMods=sm(attack=160, critChance=10),
       damageBonus=dmg(40, 60, physical=60)),
     "Strikes the earth with a thunderclap."),
    ("eschuta-temper", "Eschuta's Temper", "wand", 70,
     s(coreStats=cs(energy=20), statMods=sm(mana=80, attack=180),
       damageBonus=dmg(50, 90, fire=90)),
     "A volatile wand — temper as short as its fuse."),
    ("death-fathom", "Death's Fathom", "wand", 73,
     s(coreStats=cs(energy=20), statMods=sm(mana=80, attack=180),
       damageBonus=dmg(50, 90, cold=90), resistances=res(cold=30)),
     "A scrying-orb wand — sees deep into icy oblivion."),
    ("boneshade", "Boneshade", "wand", 63,
     s(coreStats=cs(energy=15), statMods=sm(mana=70, attack=160),
       damageBonus=dmg(40, 70, arcane=70)),
     "A bone-white wand cut from a saint's femur."),
    ("homunculus-orb", "Homunculus (Orb)", "wand", 56,
     s(coreStats=cs(energy=15), statMods=sm(mana=80, defense=40)),
     "A fetus-shaped orb that whispers spells."),
    ("the-oculus-orb", "The Oculus (Orb)", "wand", 42,
     s(coreStats=cs(energy=15), statMods=sm(mana=70, magicFind=20),
       damageBonus=dmg(20, 40, arcane=40)),
     "An orb of swirling crystal — sight beyond sight."),
    ("lacerator", "Lacerator", "axe", 68,
     s(statMods=sm(attack=210, attackSpeed=30),
       damageBonus=dmg(60, 90, physical=90)),
     "A jagged axe — every wound pours blood."),
    ("the-scalper", "The Scalper", "axe", 39,
     s(statMods=sm(attack=140, attackSpeed=20),
       damageBonus=dmg(20, 40, physical=40)),
     "Worn smooth by countless bounties."),
    ("axe-of-fechmar", "Axe of Fechmar", "axe", 8,
     s(statMods=sm(attack=60),
       damageBonus=dmg(3, 8, cold=8), resistances=res(cold=20)),
     "An icy hand-axe of barbaric make."),
    ("the-chieftain", "The Chieftain", "axe", 56,
     s(coreStats=cs(strength=20), statMods=sm(attack=180),
       damageBonus=dmg(40, 70, physical=70)),
     "A great axe of clan-leadership, well-respected."),
    ("rune-master", "Rune Master", "sword2h", 69,
     s(coreStats=cs(energy=15), statMods=sm(attack=220),
       damageBonus=dmg(70, 110, arcane=110)),
     "A rune-etched two-hander — cuts both flesh and spell."),
    ("the-cranium-basher-greater", "The Cranium Basher (Greater)", "mace", 87,
     s(coreStats=cs(strength=35), statMods=sm(attack=320, critChance=25),
       damageBonus=dmg(180, 280, physical=280)),
     "A maul of unmatched bone-shattering force."),
    ("ribcracker", "Ribcracker", "polearm", 31,
     s(coreStats=cs(strength=15), statMods=sm(attack=140, critChance=10),
       damageBonus=dmg(20, 40, physical=40)),
     "A staff that finds the gaps between ribs."),
    ("steel-driver", "Steeldriver", "sword2h", 57,
     s(coreStats=cs(strength=20), statMods=sm(attack=220),
       damageBonus=dmg(60, 100, physical=100)),
     "A maul-pole that hammers steel into the earth."),

    # More helms
    ("blackhorn-face-2", "Blackhorn's Face (Greater)", "helm", 56,
     s(statMods=sm(defense=120, attack=80),
       resistances=res(lightning=30, poison=25)),
     "A larger version of the dread mask."),
    ("vampire-gaze-greater", "Vampire Gaze (Greater)", "helm", 61,
     s(statMods=sm(defense=120, life=120, attackSpeed=10)),
     "A reforged version of the cursed gaze."),
    ("gore-burnt-skull", "Goreburnt Skull", "helm", 55,
     s(coreStats=cs(strength=15), statMods=sm(defense=100, attack=60),
       resistances=res(fire=20)),
     "A barbarian's trophy-helm, scarred by hellfire."),

    # More body armors
    ("the-vile-husk-armor", "Husk of Bones", "chest", 60,
     s(coreStats=cs(vitality=15), statMods=sm(defense=190, life=80)),
     "Bone-plates lashed with sinew — eerily light."),
    ("ondal-almighty", "Ondal's Almighty", "chest", 78,
     s(coreStats=cs(strength=20, energy=20), statMods=sm(defense=240, mana=80)),
     "An archmage's full-plate, etched with old runes."),

    # More gloves
    ("frostburn-gauntlet", "Frostburn Gauntlet", "gloves", 49,
     s(statMods=sm(defense=50, mana=40),
       resistances=res(cold=30)),
     "A frost-burned gauntlet — chills the wearer's foes."),
    ("magefist-gauntlet", "Magefist Gauntlet", "gloves", 23,
     s(coreStats=cs(energy=5), statMods=sm(mana=30, attack=40),
       damageBonus=dmg(0, 25, fire=25)),
     "A larger Vizjerei apprentice glove — fire-laced."),

    # More boots
    ("greaves-of-march", "Greaves of March", "boots", 35,
     s(coreStats=cs(strength=10, vitality=10), statMods=sm(defense=60, attackSpeed=15)),
     "A long-marcher's boots — tireless underfoot."),

    # More belts
    ("string-of-ears-greater", "String of Ears (Greater)", "belt", 55,
     s(coreStats=cs(vitality=20), statMods=sm(defense=120, life=40),
       resistances=res(physical=10)),
     "A grand grim trophy — hung with mightier ears."),

    # More rings/amulets
    ("ring-of-the-leech", "Ring of the Leech", "ring", 27,
     s(statMods=sm(life=20, mana=10)),
     "A ring fashioned from a vampire's tooth."),
    ("the-collector", "The Collector", "amulet", 43,
     s(coreStats=cs(strength=10, vitality=10), statMods=sm(magicFind=30, goldFind=80)),
     "Worn by a noble collector of relics."),
    ("the-nokozan", "The Nokozan", "amulet", 34,
     s(statMods=sm(life=30, mana=20), resistances=res(fire=20),
       damageBonus=dmg(2, 8, fire=8)),
     "A relic from a buried fire-temple."),

    # More shields
    ("lance-guard", "Lance Guard", "shield", 17,
     s(statMods=sm(defense=40, attack=40)),
     "A lancer's pavise. Punishing to charge."),
    ("kerke-sanctuary", "Kerke's Sanctuary", "shield", 67,
     s(statMods=sm(defense=200, magicDodge=20),
       resistances=res(fire=40, cold=40, lightning=40, poison=40)),
     "A massive ward of paladin-make."),

    # More 1h sword tier
    ("hellplague-greater", "Hellplague (Greater)", "sword1h", 50,
     s(statMods=sm(attack=180),
       damageBonus=dmg(40, 70, fire=35, poison=35)),
     "A blade that festers wounds with fire and rot."),
]


# ---------------------------------------------------------------------------
# Existing-id de-dup map.
#   `keep` is the canonical id we keep.
#   `drop` ids are removed entirely (their content is discarded; the
#   canonical entry from the existing dataset is preserved).
# ---------------------------------------------------------------------------
DUP_PAIRS = [
    # uniques
    ("items/unique/verdungos-hearty",      "items/unique/verdungo-cord"),
    ("items/unique/arachnids-mesh",        "items/unique/arachnid-mesh"),
    ("items/unique/gore-riders",           "items/unique/gore-rider"),
    ("items/unique/thundergods-vigor",     "items/unique/thundergod-vigor"),
    ("items/unique/tyraels-might",         "items/unique/tyrael-might"),
    ("items/unique/lavagout",              "items/unique/lava-gout"),
    ("items/unique/bul-kathos-wedding-band","items/unique/bul-kathos"),
]
SET_DUP_PAIRS = [
    ("sets/aldurs-watchtower",   "sets/aldur-watchtower"),
    ("sets/griswolds-legacy",    "sets/griswold-legacy"),
    ("sets/natalyas-odium",      "sets/natalya-odium"),
    ("sets/trang-ouls-avatar",   "sets/trang-oul-avatar"),
]


# ---------------------------------------------------------------------------
# New / completed sets — covering all 32 LoD classic+expansion sets.
# Existing partial sets in the file will be replaced entirely.
# ---------------------------------------------------------------------------

def setbonus(coreStats=None, resistances=None, statMods=None, grantsSkills=None) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    if coreStats: out["coreStats"] = coreStats
    if resistances: out["resistances"] = resistances
    if statMods: out["statMods"] = statMods
    if grantsSkills: out["grantsSkills"] = grantsSkills
    return out


def make_set(slug: str, name: str, member_keys: List[str], bonuses: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    return {
        "id": f"sets/{slug}",
        "name": name,
        "items": [f"sets/{slug}/{k}" for k in member_keys],
        "bonuses": bonuses,
    }


SETS: List[Dict[str, Any]] = [
    # === Classic 15 ===
    make_set("civerb-vestments", "Civerb's Vestments",
             ["weapon", "shield", "amulet"],
             {
                 "2": setbonus(statMods=sm(attack=100)),
                 "3": setbonus(statMods=sm(attack=150, magicFind=25)),
             }),
    make_set("cleglaw-brace", "Cleglaw's Brace",
             ["weapon", "shield", "gloves"],
             {
                 "2": setbonus(statMods=sm(attack=80)),
                 "3": setbonus(statMods=sm(physDodge=15, defense=50, attack=150)),
             }),
    make_set("iratha-finery", "Iratha's Finery",
             ["amulet", "weapon", "gloves", "helm"],
             {
                 "2": setbonus(resistances=res(fire=30, lightning=30)),
                 "3": setbonus(resistances=res(fire=40, lightning=40, cold=30)),
                 "4": setbonus(resistances=res(fire=50, cold=50, lightning=50, poison=50)),
             }),
    make_set("isenhart-armory", "Isenhart's Armory",
             ["armor", "helm", "weapon", "shield"],
             {
                 "2": setbonus(coreStats=cs(dexterity=10)),
                 "3": setbonus(statMods=sm(attack=100, defense=60)),
                 "4": setbonus(coreStats=cs(strength=15, dexterity=20),
                               statMods=sm(attack=150, defense=100)),
             }),
    make_set("sigon-complete-steel", "Sigon's Complete Steel",
             ["helm", "armor", "gloves", "belt", "boots", "shield"],
             {
                 "2": setbonus(coreStats=cs(strength=15)),
                 "3": setbonus(statMods=sm(attackSpeed=30)),
                 "4": setbonus(statMods=sm(life=50, defense=60)),
                 "5": setbonus(statMods=sm(life=80, defense=90, attack=150)),
                 "6": setbonus(coreStats=cs(strength=40, vitality=30),
                               statMods=sm(life=100, defense=120, attack=200)),
             }),
    make_set("hsarus-defense", "Hsarus' Defense",
             ["belt", "boots", "shield"],
             {
                 "2": setbonus(resistances=res(cold=25, fire=25)),
                 "3": setbonus(coreStats=cs(vitality=20), statMods=sm(defense=100)),
             }),
    make_set("cathan-traps", "Cathan's Traps",
             ["ring", "amulet", "armor", "helm", "gloves"],
             {
                 "2": setbonus(statMods=sm(magicFind=25)),
                 "3": setbonus(resistances=res(fire=50)),
                 "4": setbonus(resistances=res(fire=55), statMods=sm(magicFind=35)),
                 "5": setbonus(coreStats=cs(strength=20, dexterity=20),
                               resistances=res(fire=60),
                               statMods=sm(magicFind=50)),
             }),
    make_set("tancred-battlegear", "Tancred's Battlegear",
             ["amulet", "boots", "weapon", "armor", "helm"],
             {
                 "2": setbonus(coreStats=cs(strength=15)),
                 "3": setbonus(statMods=sm(life=40, defense=60)),
                 "4": setbonus(statMods=sm(attack=150, attackSpeed=20)),
                 "5": setbonus(coreStats=cs(strength=25, vitality=25),
                               statMods=sm(life=80, defense=120, attack=200, magicFind=20)),
             }),
    make_set("death-disguise", "Death's Disguise",
             ["sash", "gloves", "armor"],
             {
                 "2": setbonus(coreStats=cs(dexterity=15)),
                 "3": setbonus(resistances=res(poison=50),
                               statMods=sm(life=60, defense=80)),
             }),
    make_set("vidala-rig", "Vidala's Rig",
             ["boots", "amulet", "armor", "weapon"],
             {
                 "2": setbonus(coreStats=cs(dexterity=15)),
                 "3": setbonus(statMods=sm(attack=120)),
                 "4": setbonus(coreStats=cs(vitality=15, dexterity=35),
                               statMods=sm(attack=200, attackSpeed=30)),
             }),
    make_set("milabrega-regalia", "Milabrega's Regalia",
             ["weapon", "shield", "armor", "helm"],
             {
                 "2": setbonus(coreStats=cs(strength=15)),
                 "3": setbonus(statMods=sm(defense=80, life=40)),
                 "4": setbonus(coreStats=cs(strength=25, vitality=20),
                               statMods=sm(defense=150, attack=180)),
             }),
    make_set("aldurs-watchtower", "Aldur's Watchtower",
             ["helm", "armor", "boots", "weapon"],
             {
                 "2": setbonus(coreStats=cs(strength=15, vitality=15)),
                 "3": setbonus(statMods=sm(attackSpeed=40)),
                 "4": setbonus(coreStats=cs(strength=30, vitality=30, energy=20),
                               resistances=res(fire=40, cold=40, lightning=40, poison=40),
                               statMods=sm(life=150, defense=120)),
             }),
    make_set("arcanna-tricks", "Arcanna's Tricks",
             ["helm", "weapon", "armor", "amulet"],
             {
                 "2": setbonus(coreStats=cs(energy=15)),
                 "3": setbonus(statMods=sm(mana=80, defense=40)),
                 "4": setbonus(coreStats=cs(energy=25),
                               resistances=res(arcane=20),
                               statMods=sm(mana=150, attackSpeed=20)),
             }),
    make_set("arctic-gear", "Arctic Gear",
             ["armor", "belt", "gloves", "helm"],
             {
                 "2": setbonus(resistances=res(cold=50)),
                 "3": setbonus(resistances=res(cold=75), statMods=sm(defense=80)),
                 "4": setbonus(resistances=res(cold=100, fire=30),
                               statMods=sm(defense=150)),
             }),
    make_set("berserker-arsenal", "Berserker's Arsenal",
             ["helm", "armor", "weapon"],
             {
                 "2": setbonus(coreStats=cs(strength=15)),
                 "3": setbonus(coreStats=cs(strength=25, vitality=20),
                               statMods=sm(attack=150, attackSpeed=30, defense=80)),
             }),
    make_set("infernal-tools", "Infernal Tools",
             ["helm", "weapon", "gloves"],
             {
                 "2": setbonus(coreStats=cs(strength=10)),
                 "3": setbonus(resistances=res(fire=30),
                               statMods=sm(attack=120, attackSpeed=20)),
             }),
    make_set("angelic-raiment", "Angelic Raiment",
             ["amulet", "ring", "armor", "weapon"],
             {
                 "2": setbonus(coreStats=cs(strength=10)),
                 "3": setbonus(statMods=sm(life=60, defense=60)),
                 "4": setbonus(coreStats=cs(strength=20, vitality=20),
                               statMods=sm(life=120, defense=120, attack=200)),
             }),

    # === LoD 17 ===
    make_set("bul-kathos-children", "Bul-Kathos' Children",
             ["weapon1", "weapon2"],
             {
                 "2": setbonus(coreStats=cs(strength=40, vitality=30),
                               statMods=sm(attackSpeed=50, life=200, attack=300)),
             }),
    make_set("cow-king-leathers", "Cow King's Leathers",
             ["helm", "armor", "boots"],
             {
                 "2": setbonus(coreStats=cs(strength=15)),
                 "3": setbonus(coreStats=cs(strength=25, vitality=20),
                               statMods=sm(defense=120, magicFind=40)),
             }),
    make_set("disciple", "Disciple",
             ["helm", "armor", "amulet", "ring", "boots", "belt", "gloves"],
             {
                 "2": setbonus(coreStats=cs(vitality=10)),
                 "3": setbonus(coreStats=cs(vitality=15), statMods=sm(life=60)),
                 "4": setbonus(resistances=res(fire=20, cold=20, lightning=20, poison=20)),
                 "5": setbonus(statMods=sm(defense=120, life=100)),
                 "6": setbonus(coreStats=cs(strength=20, dexterity=20)),
                 "7": setbonus(coreStats=cs(strength=30, vitality=30),
                               statMods=sm(life=200, defense=200, magicFind=40),
                               resistances=res(fire=30, cold=30, lightning=30, poison=30, arcane=30)),
             }),
    make_set("griswolds-legacy", "Griswold's Legacy",
             ["helm", "armor", "shield", "weapon"],
             {
                 "2": setbonus(statMods=sm(defense=100, attackSpeed=20)),
                 "3": setbonus(resistances=res(fire=40, cold=40, lightning=40, poison=40)),
                 "4": setbonus(coreStats=cs(strength=30, vitality=30),
                               resistances=res(fire=60, cold=60, lightning=60, poison=60),
                               statMods=sm(defense=200)),
             }),
    make_set("heaven-brethren", "Heaven's Brethren",
             ["helm", "armor", "weapon", "shield"],
             {
                 "2": setbonus(statMods=sm(defense=80)),
                 "3": setbonus(resistances=res(fire=20, cold=20, lightning=20, poison=20)),
                 "4": setbonus(coreStats=cs(strength=25, vitality=20),
                               statMods=sm(defense=200, attack=200)),
             }),
    make_set("hwanin-majesty", "Hwanin's Majesty",
             ["helm", "armor", "weapon", "belt"],
             {
                 "2": setbonus(statMods=sm(attackSpeed=20)),
                 "3": setbonus(resistances=res(lightning=30, cold=30)),
                 "4": setbonus(coreStats=cs(dexterity=20, vitality=20),
                               statMods=sm(attack=180, attackSpeed=40),
                               damageBonus=None) if False else setbonus(
                              coreStats=cs(dexterity=20, vitality=20),
                              statMods=sm(attack=180, attackSpeed=40)),
             }),
    make_set("immortal-king", "Immortal King",
             ["helm", "armor", "gloves", "belt", "boots", "weapon"],
             {
                 "2": setbonus(coreStats=cs(vitality=25)),
                 "3": setbonus(statMods=sm(attackSpeed=50)),
                 "4": setbonus(statMods=sm(attack=150, defense=100)),
                 "5": setbonus(resistances=res(fire=40, cold=40, lightning=40)),
                 "6": setbonus(coreStats=cs(strength=50, dexterity=50, vitality=50, energy=50),
                               statMods=sm(life=200, defense=200, attack=300)),
             }),
    make_set("mavina-battle-hymn", "M'avina's Battle Hymn",
             ["helm", "armor", "belt", "gloves", "weapon"],
             {
                 "2": setbonus(coreStats=cs(dexterity=20)),
                 "3": setbonus(statMods=sm(attackSpeed=30)),
                 "4": setbonus(statMods=sm(attack=180, magicFind=30)),
                 "5": setbonus(coreStats=cs(vitality=25, dexterity=50),
                               statMods=sm(attack=250, attackSpeed=50, magicFind=50)),
             }),
    make_set("naj-ancient-vestige", "Naj's Ancient Vestige",
             ["armor", "weapon", "helm"],
             {
                 "2": setbonus(statMods=sm(defense=120)),
                 "3": setbonus(coreStats=cs(energy=40),
                               statMods=sm(mana=150, defense=180)),
             }),
    make_set("natalyas-odium", "Natalya's Odium",
             ["helm", "armor", "boots", "weapon"],
             {
                 "2": setbonus(coreStats=cs(dexterity=20)),
                 "3": setbonus(statMods=sm(critChance=15)),
                 "4": setbonus(coreStats=cs(vitality=20, dexterity=40),
                               resistances=res(fire=30, cold=30, lightning=30, poison=50),
                               statMods=sm(attackSpeed=40, critDamage=50)),
             }),
    make_set("orphan-call", "Orphan's Call",
             ["helm", "armor", "gloves", "weapon"],
             {
                 "2": setbonus(coreStats=cs(strength=15, vitality=15)),
                 "3": setbonus(statMods=sm(life=80, defense=100)),
                 "4": setbonus(coreStats=cs(strength=40, vitality=30),
                               statMods=sm(life=150, defense=150)),
             }),
    make_set("sander-folly", "Sander's Folly",
             ["gloves", "boots", "weapon"],
             {
                 "2": setbonus(coreStats=cs(dexterity=15)),
                 "3": setbonus(statMods=sm(attack=150, attackSpeed=40)),
             }),
    make_set("sazabi-grand-tribute", "Sazabi's Grand Tribute",
             ["helm", "armor", "weapon"],
             {
                 "2": setbonus(coreStats=cs(strength=15)),
                 "3": setbonus(coreStats=cs(strength=25, vitality=20),
                               statMods=sm(attack=180, defense=120)),
             }),
    make_set("tal-rashas-wrappings", "Tal Rasha's Wrappings",
             ["amulet", "armor", "helm", "belt", "weapon"],
             {
                 "2": setbonus(coreStats=cs(energy=10)),
                 "3": setbonus(statMods=sm(mana=60, attackSpeed=20)),
                 "4": setbonus(resistances=res(fire=20, cold=20, lightning=20, poison=20)),
                 "5": setbonus(coreStats=cs(energy=20, vitality=15),
                               statMods=sm(mana=150, attackSpeed=30, defense=120),
                               resistances=res(fire=40, cold=40, lightning=40, poison=40, arcane=40)),
             }),
    make_set("trang-ouls-avatar", "Trang-Oul's Avatar",
             ["helm", "armor", "gloves", "belt", "shield"],
             {
                 "2": setbonus(resistances=res(poison=50)),
                 "3": setbonus(statMods=sm(mana=100)),
                 "4": setbonus(coreStats=cs(energy=20), statMods=sm(defense=100)),
                 "5": setbonus(coreStats=cs(energy=30, vitality=30),
                               resistances=res(fire=40, cold=40, lightning=40, poison=100),
                               statMods=sm(defense=150, mana=150)),
             }),
]


# ---------------------------------------------------------------------------
# Build & write
# ---------------------------------------------------------------------------

def main() -> None:
    with open(UNIQUES_PATH, "r", encoding="utf-8") as fh:
        existing_uniques = json.load(fh)

    # Drop dup ids on the unique side.
    drop_unique_ids = {drop for _keep, drop in DUP_PAIRS}
    deduped_uniques = [u for u in existing_uniques if u["id"] not in drop_unique_ids]

    existing_ids = {u["id"] for u in deduped_uniques}

    # Append new uniques that don't collide with what we already have.
    new_count = 0
    for slug, name, slot, req, stats, flavor in NEW_UNIQUES:
        item_id = f"items/unique/{slug}"
        if item_id in existing_ids:
            continue
        base_id = base_for(slot, req)
        entry: Dict[str, Any] = {
            "id": item_id,
            "name": name,
            "baseId": base_id,
            "reqLevel": req,
            "stats": stats or {},
        }
        if flavor:
            entry["flavor"] = flavor
        deduped_uniques.append(entry)
        existing_ids.add(item_id)
        new_count += 1

    # Sort by reqLevel asc, then name asc.
    deduped_uniques.sort(key=lambda x: (x["reqLevel"], x["name"]))

    # Sets — drop duplicates entirely; replace with our authoritative SETS list.
    new_set_ids = {ss["id"] for ss in SETS}
    # Keep any existing set NOT in our new list (defensive — but we expect to overwrite all).
    with open(SETS_PATH, "r", encoding="utf-8") as fh:
        existing_sets = json.load(fh)

    drop_set_ids = {drop for _keep, drop in SET_DUP_PAIRS}
    # Discard duplicates AND any set we are replacing.
    kept_existing_sets = [
        s for s in existing_sets
        if s["id"] not in drop_set_ids and s["id"] not in new_set_ids
    ]
    final_sets = kept_existing_sets + SETS
    final_sets.sort(key=lambda x: x["name"])

    with open(UNIQUES_PATH, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(deduped_uniques, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    with open(SETS_PATH, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(final_sets, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    print(f"Uniques: existing kept={len(deduped_uniques)-new_count} new={new_count} total={len(deduped_uniques)}")
    print(f"Sets:    kept-existing={len(kept_existing_sets)} new/replaced={len(SETS)} total={len(final_sets)}")


if __name__ == "__main__":
    main()
